### ISSUE TITLE
Re-evaluate adding NSZ support

### ISSUE THREAD

**Issue by redthing1** [yuzu-emu/yuzu#10025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I was wondering if adding NSZ support could be [re-evaluated](https://github.com/yuzu-emu/yuzu/issues/3245#issuecomment-955005075).

### Why would this feature be useful?

 File sizes are big these days and it would help a lot to support a compressed format.

**Comment by yuwenhua653** [comment]
It has been stated before that these compression formats are related to piracy, and yuzu will not support them

**Comment by Ritaku02** [comment]
Proof of that? I find it hard to believe that a compression format is related to piracy in any way, and compression has a LOT of *very legitimate* purposes. It sounds like a cop-out to me. Not to mention it's perfectly possible, and rather easy, to convert between NSP/XCI and NSZ/XCZ, and If I can keep my *legally-bought* games in a compressed state so they're not eating up tons of drive space, I'd prefer that.

**Comment by redthing1** [comment]
> It has been stated before that these compression formats are related to piracy, and yuzu will not support them

Respectfully, that is a very stupid answer.

I personally use nsz because game dumps can be quite large and don't compress without decryption. It would be nice to be able to play them without decompressing.

Finally,
piracy is based

**Comment by yuwenhua653** [comment]
Previously, yuzu has stated that it will not support compressed formats
https://github.com/yuzu-emu/yuzu/issues/8515
Also ryujinx won't support them either
https://github.com/Ryujinx/Ryujinx/issues/1185
Don't put emulator at legal risk for convenience

**Comment by redthing1** [comment]
> > It has been stated before that these compression formats are related to piracy, and yuzu will not support them
> 
> Even if all anti-consumer pro-global-monopoly propaganda is true and all abandonware preservationists are evil inhuman goblins that live to make poor monopoly-men cry from being forced to wait 1-day longer for purchasing a new mega-yacht due to decreased opportunities for fleecing cornered anti-competitive price-fixed stagnated market… what is it to you? Does this project exist for the sole purpose of making 80-year old Nintendo's litigious office dinosaurs, that love to attack even their own fans who make free advertisements for their products, happier? This take is absurdly comedic and tragic.
> 
> If someone feels sinful from believing this, they better off adding contextual ads and donation links for studios that developed discovered ROMs instead of serving as free-of-charge PR and enforcement agents of predatory distributors/"labels" of our corporatocratic hellscape.

Very based and well said

**Comment by Helios747** [comment]
lmfao wanting to save space is only a pirate's desire?

christ that is some insane logic y'all are cookin' up here.

**Comment by FearlessTobi** [comment]
Just to give some closure on this, it is not so much us being against compression formats, it is that NSZ has *terrible* performance for random file access.
Those access times are very important for yuzu and that's why we will never add native support for NSZ to the emulator.
If someone comes up with a better way of compressing Switch games in the future, I see no reason why we shouldn't support it.

**Comment by FernandoS27** [comment]
I'll give a response on this concern.

Some people would love to keep all their dumps as small as possible and save disk space on their storage. This here is a valid concern. HOWEVER, NSZ is not a format designed in such way that can be useful.

NSZ is not a good compressed storage format because:

- You cannot access the game files within it randomly, you must decompress the full storage, in order, to access them.
- The decompression algorithm is way too slow, at 100MB/s.
- Since it must be fully decompressed in order to be read. A temporary decompressed storage must be created or RAM must be allocated just for the storage. defeating the purpose of saving space as a decompressed NSP can easily grow to 10Gb or more.
- NSZ format's main purpose is for mass sharing, thus is associated with piracy.
