### ISSUE TITLE
Why doesn't the YUZU emulator have a real-time update check feature? 

### ISSUE THREAD

**Issue by 123shuhai** [yuzu-emu/yuzu#10102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I want to know if it's possible to add a 'Check for Updates' feature in the 'Help' tab of the YUZU emulator, so that updates can be checked in real time without having to download from the official website every time. 

### Why would this feature be useful?

Also, why does this emulator update so frequently? It seems like there's an update every two or three days, but I don't see any changes after updating. I thought that you were discovering a small problem and then updating the emulator each time, but it doesn't seem necessary. In my opinion, updates could come more slowly, every 10 days to two weeks, so that more issues could be discovered and addressed.

**Comment by german77** [comment]
If you use our installer it will check for updates at boot and download the latest version automatically. Yuzu is in active development. 

We update every day because we need to, in average we do 40+ commits a month. Spacing updates every 10 days will slow down the project a lot, just imagine keeping track of the regressions of 10 different changes at once then having to wait 10 days to fix those issues.

Take a look at https://github.com/yuzu-emu/yuzu-mainline/releases if you want to see the changes of every version

**Comment by 123shuhai** [comment]
"I understand now, it turns out that I misunderstood."
