### ISSUE TITLE
Xenoblade 3 Future Redeemed Graphical Bugs

### ISSUE THREAD

**Issue by PotateScratcher** [yuzu-emu/yuzu#10115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3535

### Description of Issue

Xenoblade 3 Future Redeemed has numberous visual glitches on OpenGL (vulkan is busted on both emulators). Vertex explosions, texture flickering, and red and blue light flashing occur in different areas

### Expected Behavior

None of the above

### Reproduction Steps

This always happens, included save files will take you straight to aurora shelf where the worst of it I have encountered so far is.
[XC3FR_Saves.zip](https://github.com/yuzu-emu/yuzu/files/11359851/XC3FR_Saves.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11359848/yuzu_log.txt)

### System Configuration

CPU: i512400
GPU/Driver: 6600xt/AMDGPU
RAM: 16GB
OS: Pop! Os 22.04

**Comment by grimkor** [comment]
To bolt on to this issue I've tried Vulkan on the Steam Deck (AMD) where it will not get past the loading screen after the Future Redeemed main menu. 

Tried a lot of different settings and removing caches with no success. Worth knowing that the base game does load.

**Comment by goldenx86** [comment]
We don't have a way to bypass the lack of D24 support on AMD hardware, it needs to be at least emulated via drivers.

**Comment by grimkor** [comment]
> We don't have a way to bypass the lack of D24 support on AMD hardware, it needs to be at least emulated via drivers.

Thanks for the detailed reason, good to know and appreciate the response.

**Comment by PotateScratcher** [comment]
Adding additional information that was discussed in discord for visibility:

These are opengl issues that are not present in Ryujinx, so while the Vulkan issues are likely AMD hardware related, the OpenGL problems are likely not.

Seizure warning:

[Screencast from 04-29-2023 05:42:02 PM.webm](https://user-images.githubusercontent.com/120071575/235327031-ec709a27-11a5-4528-ba14-2ad86a738812.webm)

**Comment by PotateScratcher** [comment]
apologies, didn't intend to close

**Comment by goldenx86** [comment]
Yeah we have to look into OpenGL.

**Comment by scol1951** [comment]
yuzu 140X ~141X                           yuzu 3537 
![스크린샷 2023-05-01 19-06-43](https://user-images.githubusercontent.com/110660270/235439165-074e2ca1-69dc-45d2-8f04-2a58bfa521f7.png)


ubuntu -12.04 ~ 13.04
ubuntu default driver
AMD 5800x 
32g ram
AMD rx5700
ubuntu default driver

Running with Ubuntu, it's hard to find bugs in yuzu. Probably because my GPU is RDNA1.

**Comment by jenkshi** [comment]
related to steam deck. Xenobalde 3 preformance is so bad right now, I get 4 fps I am in yuzu ver 1416 using vulkan . I have wave 4 installed and  update 2. this is in the normale game I didn't try Future Redeemed

**Comment by bbogdn2** [comment]
I'm no expert in the problem related, but I think the [d24 depth issue thread](https://github.com/xenia-project/xenia/issues/756) in the xenia project might be worth a read.

**Comment by RoaminGrape** [comment]
I'm still getting explosions on an i7-12700F w/RTX3080 regardless of setting, nvidia control setting, or API on EA3820.

**Comment by lucianobraga84** [comment]
Well, I saw that two months ago it was said that the problem was not exactly the issue of D24 support, but something even deeper in the structure of AMD GPUs themselves.

I thought this point would be discussed further in this month's blogpost, but it was not mentioned.

The question I'm going to ask is simple and don't take it as pressure, because it's mere curiosity: what is the real problem and is it "fixable" on AMD GPUs?

If the developers can additionally provide an overview of the issue, I would also appreciate it.

**Comment by DuIslingr** [comment]
bump for a response to the above post

**Comment by PotateScratcher** [comment]
An update, some of the recent OpenGL fixes resolved the red/blue grass flickering for me.
