### ISSUE TITLE
Android: Mark Yuzu app as a game

### ISSUE THREAD

**Issue by sharpy66** [yuzu-emu/yuzu#10714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Mark the Yuzu app as a game on the play store. 

### Why would this feature be useful?

Would allow more android OEM game booster services to affect the Yuzu app, potentially improving performance.

**Comment by Roydpeter** [comment]
I should mention that this will affect Samsung phones negatively. The gameoptimizingservice will throttle any app marked as a game and won't allow any high clocks in order to keep the temperatures down for long periods of time. It's so freaking bad because it results in games running at half speed on Samsung devices.

**Comment by sharpy66** [comment]
Some people have mentioned that turning on the "Alternative game performance management" option in samsungs game booster helps with performance significantly. I made this request because my phone is being thermal throttled horribly and it leads to me getting a 3rd the fps that others with similar hardware are getting.  Maybe the game booster with that option on will make a positive difference.

**Comment by nitanmarcel** [comment]
There's also the game mode API provided by the sdk on Android 13, I wonder if that will also bring any improvements regarding the performance

https://developer.android.com/games/gamemode/gamemode-api

**Comment by sharpy66** [comment]
> There's also the game mode API provided by the sdk on Android 13, I wonder if that will also bring any improvements regarding the performance
> 
> [developer.android.com/games/gamemode/gamemode-api](https://developer.android.com/games/gamemode/gamemode-api)

Or if samsung is using that to force the "Battery" mode, then the Yuzu app could opt out, or manually force the performance mode.

**Comment by nitanmarcel** [comment]
> > There's also the game mode API provided by the sdk on Android 13, I wonder if that will also bring any improvements regarding the performance
> > [developer.android.com/games/gamemode/gamemode-api](https://developer.android.com/games/gamemode/gamemode-api)
> 
> Or if samsung is using that to force the "Battery" mode, then the Yuzu app could opt out, or manually force the performance mode.

I suppose Samsung uses their own implementation, but I'm not sure. I've found a page on Samsung's docs but it mentions Unity

https://developer.samsung.com/galaxy-gamedev/overview.html

**Comment by nitanmarcel** [comment]
Tho I suppose I've found how unity handles Samsung's GameSDK

https://github.com/needle-mirror/com.unity.adaptiveperformance.samsung.android

**Comment by t895** [comment]
Addressed by #11378

Also just to talk about other parts of this thread

> Or if samsung is using that to force the "Battery" mode, then the Yuzu app could opt out

We would have to implement these performance tiers as shown by the [game mode API](https://developer.android.com/games/gamemode/gamemode-api) for any kind of forced change to happen. Since we don't currently handle *any* of the shown cases, we will always use maximum performance. However, we can't control what Samsung does (or any other OEM) behind the scenes to throttle your device.

We also can't guarantee that your phone's specific game launcher will respond to yuzu. It really can just come down to an allowlist that the manufacturer has to update on their own time. So far, the best way to trigger any given game mode is to install the app from the play store.
