### ISSUE TITLE
Pikmin 1 Oddly Demanding of the GPU

### ISSUE THREAD

**Issue by ReporterNotCoder** [yuzu-emu/yuzu#11001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1482

### Description of Issue

I thought the "emulation within emulation" games struggled mostly cause they were too CPU intensive. But in Pikmin 1's case, I seem to be losing performance due to the GPU not keeping up, while the CPU seems fine. What makes it more weird is that Pikmin 2 actually runs at a constant 30fps. Any idea why this may be happening?

![image](https://github.com/yuzu-emu/yuzu/assets/138178907/3449934a-b08b-4484-994e-32059567b209)

### Expected Behavior

Since it's "emulation within emulation" I expected it to be more CPU intensive, not the other way around. Still, it seems more likely that the GPU is being filled with unnecessary fluff and an optimization patch should fix it.

### Reproduction Steps

Just take out 100 pikmin in the forest of hope and walk around, FPS will drop randomly in some areas, especially in the starting one with the ship and onions. It also drops when you open the map for some reason.

Save file:
[0100AA80194B0000.zip](https://github.com/yuzu-emu/yuzu/files/11931493/0100AA80194B0000.zip)

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11931494/yuzu_log.txt.old.txt)

### System Configuration

CPU: Ryzen 5 3600
GPU: RX 580 8gb
GPU/Driver: 23.3.1
RAM: 2 * 8gb DDR4
OS: Windows 10

**Comment by Squall-Leonhart** [comment]
framebuffer readbacks.

**Comment by FearlessTobi** [comment]
You are using a relatively old GPU.
100% utilization can be expected in some titles.

**Comment by Squall-Leonhart** [comment]
It's not the age of the gpu, but rather the vendor of the gpu.

> The game is using invalid vertex buffer strides (according to the Vulkan spec). The emulator has code to convert the vertex buffer data to something with valid stride. Because those invalid strides have been confirmed to work fine on NVIDIA, the conversion is not enabled on NVIDIA, but is enabled on other vendors. The problem is that the game updates vertex data often, and uses very large vertex buffer sizes. This causes the conversion to take a long time on every frame.

**Comment by RecentRunner** [comment]
Is there a way to disable invalid buffer strides on AMD gpus? I've been reading the issue from Ryujinx's side and they have a similar issue. https://github.com/Ryujinx/Ryujinx-Games-List/issues/4653

I can confirm on both my AMD Desktop PC and my Steam deck I still have the same issue with performance and audio hitching. Pikmin 2 works perfectly fine as well as 3 and 4 for the most part. The issue is specifically with Pikmin 1. To back up what Squall-Leonhart said it seems to me that the issue is the vendor rather than the age of the GPU.

Every few seconds the audio completely cuts out and hitches for about half a second and then goes back to normal afterwards

@FearlessTobi Will you please consider reopening this issue? I don't think it's resolved yet and I can still reproduce it in both mainline as well as the early access builds

**Comment by RecentRunner** [comment]
I had regularly been checking whether this issue persisted by loading up the latest early access build on my steam deck every few weeks. As of Yuzu 3988 and beyond the issue has seemed to be fixed? Or at the very least mitigated to the point where I can't notice it anymore when playing on my steam deck
