### ISSUE TITLE
Faster ASTC texture decoding (suggestion)

### ISSUE THREAD

**Issue by hugo-sna** [yuzu-emu/yuzu#11105]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What feature are you suggesting?

I'm not sure if I'm at the right place to give this idea, I'm not that good at C++ programming for PC so I just give my idea to have faster ASTC texture decoding. I've read on one [blog posts](https://yuzu-emu.org/entry/yuzu-progress-report-feb-2023/) that ASTC texture is very slow and couldn't really be accelerated. Here's my idea to accelerate it, I'm not sure if it's possible because I don't much about graphics/GPU programming but the idea is instead of using the main GPU it could use the integrated Intel GPU to decode the ASTC textures because since Skylake, Intel support full ASTC texture decoding (on their integrated GPU). I hope you like the idea I'm not sure if it's even possible, I'm not a professional.

### Why would this feature be useful?

Make games run smoother or more accurately

**Comment by goldenx86** [comment]
The main limitation of this approach would be the time it takes to transfer over PCIe.

**Comment by liamwhite** [comment]
We decode ASTC using compute shaders on GPUs which don't support ASTC.

There are a number of issues with using the integrated GPU to decode ASTC, including that making it work with OpenGL would be rather difficult, and it would require a significant rearchitecting of the current Vulkan backend to support multiple devices. I don't expect it to be that much faster, because we'd have to then transfer uncompressed image data to the dedicated GPU.

**Comment by hugo-sna** [comment]
Thanks for the explanation, I don't know if I should close the issue or wait until someone closes it
