### ISSUE TITLE
Stetting default handheld or docked per game

### ISSUE THREAD

**Issue by KokkichiOma** [yuzu-emu/yuzu#11325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Stetting default handheld or docked per game
Below concept art
![image](https://github.com/yuzu-emu/yuzu/assets/73794915/2ab784ff-8d2b-4025-905f-17d59cfcc30b)

### Why would this feature be useful?

Different games on the same hardware need different settings to perform better or to have better graphics. Changing these settings every time when opening a game is annoying, and this could be a good quality of life improvement.

**Comment by german77** [comment]
This should be already implemented. If you set a handheld controller profile on per game settings it will automatically swap to handheld for that game

**Comment by lat9nq** [comment]
I believe there's still merit in having the setting available standalone. Some games I prefer 2x handheld and others **need** 1x due to emulator issues so I use docked on those.

Your suggestion also assumes you're using the same controller all the time, or are willing to make handheld variants for all the controllers you own.

**Comment by KokkichiOma** [comment]
My suggest focuses only to changing automatically this mode that mostly affect graphic.
![image](https://github.com/yuzu-emu/yuzu/assets/73794915/1914c9df-80de-4071-8346-9391f860960b)
