### ISSUE TITLE
希望支持iOS  

### ISSUE THREAD

**Issue by gonjudaren** [yuzu-emu/yuzu#11417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

苹果ios一直都没有啊 希望支持

### Why would this feature be useful?

苹果iOS版

**Comment by liamwhite** [comment]
Even if the JIT restriction on applications was lifted or otherwise able to be worked around, the address space limitations on iOS make it impossible to implement 39-bit fastmem, so it would require pure software memory translation, making the performance would be abysmal. This is not the case on Android, since we have access to JIT and can make 39-bit address spaces without issue.

**Comment by austinarchibald** [comment]
What about Vision Pro? M2 16GB RAM. Would love to run Yuzu natively rather than streaming from my gaming PC.

**Comment by liamwhite** [comment]
Vision Pro does not allow JIT to my knowledge

**Comment by austinarchibald** [comment]
> Vision Pro does not allow JIT to my knowledge

FYI someone got [JIT working](https://www.reddit.com/r/VisionPro/comments/1awx0hj/dolphinios_works/) on DolphinvOS.
