### ISSUE TITLE
Suggestion: Infrequent releases compatible with Win7 (every 3 mo, 6 mo, or 1 yr)

### ISSUE THREAD

**Issue by pullblox39** [yuzu-emu/yuzu#11432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Once every 3 months, 6 months, or 1 year, release a Yuzu compatible with Windows 7.

A schedule this infrequent should be a reasonable compromise with Windows 7 users. It's much lower-maintenance for Yuzu devs than the current Windows schedule, doesn't necessitate further or general Windows 7 support, and may not require more than a Qt5 build with backwards-incompatible updates reverted (like this one):

https://github.com/yuzu-emu/yuzu/issues/9952

The cost of dev time weighed against the benefit to Windows 7 users seems strongly right-sided. At the very least, this should be heard by Yuzu devs before being closed.

### Why would this feature be useful?

This feature would be useful for Windows 7 users who, while small in percent, are large in number for a program as popular as Yuzu. As a user myself, the last compatible Yuzu version is my only app to regularly crash my system. Each crash risks corrupting my drives, compelling me to buy backup storage with money that'd otherwise go to Yuzu. For a Windows 7 user, there's no feature greater than making the program work.

I intend to play over 100 games for the Switch. For this feature I could in exchange file bug reports on affected games, fixes for which are useful for the development, audience, reputation, and financing of Yuzu. Other Windows 7 users may contribute as well, and fixes for one issue can sometimes solve different issues in other games to raise compatibility across the board.

**Comment by german77** [comment]
Windows 7 reached it's end of life on 2020. We will not focus compatibility or keep an alternative build just to support users who refuse to update once in 10 years.

Feel free to modify the source and try to make it work.

**Comment by gidoly** [comment]
while we appreciate asking feature nicely. Currently, Our cpu emulation  utilize features from later version of windows 10, since this is heavily tied to our core part of emulation. it can't be easily reverted or fixed. There was many changes added top on that reverting these behavior may screw up emulation functionality. It is also very challenging to support outdated os. Multi os support sounds good but it means devs need to test more hardware variation that commonly used by those os, and most of windows 7 systems are below our minimum requirement. Windows 7 gpu driver support is out of date, it will cause lot of issues in future (and currently) as we consistantly utilize new features for out gpu developement. for these reason we are not gonna going to publish windows 7 support build, hope you understand

**Comment by Squall-Leonhart** [comment]
The current QT6release is also not compatible with 7, and this will be used at some point in the future to resolve some localisation issues with font rendering.

**Comment by FernandoS27** [comment]
Just disable fastmem optimizations on the CPU settings that's it.

Or install Linux
