### ISSUE TITLE
direct translation of Vulkan calls?

### ISSUE THREAD

**Issue by Mis012** [yuzu-emu/yuzu#12310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I assume there is some reason that games which use Vulkan can't have their Vulkan calls sent directly to Mesa (or a thin layer around it if Mesa didn't want to carry switch extensions), but searching the internet I wasn't able to find any information on this. Is there a Vulkan loader on the switch? Is it statically linked in? Is the whole driver statically linked in like with switch-mesa?

### Why would this feature be useful?

If this is possible, it would obviously remove a lot of overhead for games which use Vulkan.

**Comment by bylaws** [comment]
This is possible, however like four games ship using vulkan, and all but SM3DAS have native pc ports.

**Comment by Mis012** [comment]
well, they definitely don't have native aarch64 Linux ports (or even WoA ports to use with Wine), and with NCE and direct Vulkan translation that would mean the switch version should easily perform better than emulating the x86 version. But if the number is still 4 even including games with PC ports, that would be hard to justify spending much effort on...

Not sure if any games use OpenGL, I've seen mixed reports on whether that is supported, could obviously do the same thing there.

I don't know how annoying would the NVN thing be to translate vkd3d style, but it should probably still have less overhead than emulating the whole GPU (though again it's possible that it's statically linked in such a way that it would be near impossible to find the separation between the game and the API calls)

**Comment by liamwhite** [comment]
1. Getting the calls in the first place

yuzu has ways of interacting with the executing guest program, but "function calls" are not one of them. The guest program interacts with the emulator by issuing supervisor call instructions which direct the emulated kernel to do something on its behalf (typically IPC). Graphics drivers are not very IPC driven, and use it for command buffer submission and presentation. This means getting the call would necessarily involve some sort of preprocessing of the guest program to find how the program discovers the Vulkan API. I have previously found that the library provided by Nvidia exposes vkGetInstanceProcAddr, but also directly exposes all Vulkan API functions it has, and these are imported directly by games like Super Mario 3D All-Stars. So we would need to discover calls both as function pointers returned from vkGetInstanceProcAddr, and also functions which are directly called. Yet another complication is that at least Super Mario Galaxy is actually 32-bit, so we need to also be able to do this for 32-bit games (meaning this would also need to work with Dynarmic). Even if we were running on NCE and redirected the function call in the 64-bit case, we would still need a distinct mechanism for handling the 32-bit case on Dynarmic. And it wouldn't make any sense to have this redirection limited to 64-bit NCE--we'd want to have it for 64-bit Dynarmic too so that desktop can benefit. This isn't *too* bad though.

2. Window system integration

The core Vulkan API does not define a method for presentation to the screen. This is the role of the WSI extensions, and the Vulkan WSI for the Switch is rather [typical](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#platformCreateSurface_vi). However, this cannot be used for direct presentation to the render window in yuzu's case, because all three of the 3D All-Stars games use window crop parameters which do not have standard representations (and might not even be possible except on Android or Switch WSI). This means they would have to be bypassed completely in favor of our own compositor emulation. Speaking of the compositor, because yuzu runs on a wide variety of devices, triple-buffered compositing (`VK_PRESENT_MODE_MAILBOX_KHR`) is not always available on all devices, and most games use this mode, so we would have to emulate the entire WSI anyway to provide the semantics the program is looking for.

3. Vendor extensions

Games use API calls containing Nvidia extensions to the Vulkan specification. What are we supposed to do about this? Many of the 3D engine configurations we already do emulate have evolved into independent standards, but some stuff like ViewportSwizzleNV is infeasible without hardware support.

4. Rescaling

All Vulkan games upload their shader modules in SPIR-V format. The way yuzu supports rescaling is a byproduct of the process of disassembling Maxwell shader binaries and observing their control flow. It is _possible_ for yuzu to parse the SPIR-V binaries in this case, but this would mean we would be taking a _completely_ unique control flow path to parse it and insert the resolution scaling code, and also would need to import SPIR-V libraries to parse SPIR-V. Otherwise, resolution scaling simply cannot be supported when passing through Vulkan.

5. Oh god the textures

Even putting aside the problems with ASTC textures for a moment, and assuming that we can cooperate fully with the game to allocate our own Vulkan resources from the host into the guest (which we can't always, but that would make this response even longer and it's already way too long), by far the most significant issue with passthrough emulation of guest graphics APIs is the textures. Nvidia stores textures in the block linear format, which is a tiled texture format designed for optimization of spatial locality. Only Nvidia uses the block linear format. Other vendors use their own [Morton](https://en.wikipedia.org/wiki/Z-order_curve) curves with different tiling parameters. Most games map image memory and dump pre-tiled textures from their RomFS directly into that memory--they aren't using commands along the likes of vkCmdCopyBufferToImage (which would tile the unaligned linear image data into the destination). This means that in practice _all accesses to image memory have to be trapped so that the data can be tiled or untiled_.
