### ISSUE TITLE
Compilation fails on MSYS2

### ISSUE THREAD

**Issue by MajorP93** [yuzu-emu/yuzu#12723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All recent

### Description of Issue

When following the steps in the official Yuzu Windows MSYS2 compilation howto there are 2 build errors that are preventing the compilation to succeed.

```
C:/Users/Philipp/git/yuzu-mainline/src/common/fs/file.h:40:25: error: no matching function for call to 'std::basic_ifstream<char>::open(std::u8string, std::ios_base::openmode&)'
   40 |         file_stream.open(ToU8String(path), open_mode);
```

and 

```
C:/msys64/mingw64/include/c++/13.2.0/fstream:988:9: error: 'class std::__cxx11::basic_string<char8_t>' has no member named 'make_preferred'
```

When following the official howto, GCC for Windows is being used in MSYS2. To me it appears this makes compilation following a different path compared with using MSVC. On Linux the invocation of ToU8String(path) appearently is not needed which probably is the reason why GCC is working there.
Please fix this issue so we can get more optimized builds on Windows.

### Expected Behavior

The build finishing without errors.

### Reproduction Steps

Trying to build on Windows using MSYS2.

### Log File

Please find the relevant parts above (issue description).

### System Configuration

CPU: irrelevant
GPU/Driver: irrelevant
RAM: irrelevant
OS: Windows 10

**Comment by merryhime** [comment]
If anyone is wondering what the root cause of the second error is, gcc is picking up the [4th `open` overload](https://github.com/gcc-mirror/gcc/blob/c891d8dc23e1a46ad9f3e757d09e57b500d40044/libstdc%2B%2B-v3/include/std/fstream#L988) which fails by SFIANE. This is correct and expected behaviour.

What is not is not having any alternative to that overload. I note the standard doesn't specify any `std::u8string` overloads.

Does using `std::filesystem::u8path` instead of `ToU8String` not work?
