### ISSUE TITLE
Install location option for the installer

### ISSUE THREAD

**Issue by cascardian** [yuzu-emu/yuzu#1574]
I imagine there is already awareness of this particular request in the team, so this is just for the record. Currently, the installer automatically picks the user's local appdata folder. As in Citra, there should ultimately be a way to choose the installation folder.

**Comment by FearlessTobi** [comment]
This is feature missing, is done by design. We've had major issues with custom install locations for Citra, like a user deleting all their files on the Desktop, cause they used it as the install location and wanted to uninstall Citra.
If you want a custom location, your only option is not to use the installer.

Requesting to close
