### ISSUE TITLE
Unity games run too fast

### ISSUE THREAD

**Issue by imxieyi** [yuzu-emu/yuzu#1821]
Games that are developed in Unity3D, e.g. [KAMIKO](https://yuzu-emu.org/game/kamiko/) and [Little Dragon's Cafe](http://www.littledragonscafe.com/) run at a ridiculously high speed (about 20x) although it is shown to run at no higher than 100% and 60 fps. The audio is still at normal speed in both games. These games should be fully playable if the speed is normal.

yuzu version: Canary 1642 | HEAD-d7c837f

**Comment by Hexagon12** [comment]
This issue is not restricted to Unity only and happens in Unreal Engine games (also, Pokemon Quest was made in Unity and doesn't have the timing issues).

**Comment by legoj15** [comment]
As referenced in #1996, Pokémon Let's GO has possibly related speed issues too, and so does Kirby Star Allies (at least on the title screen from what I've been able to see)

**Comment by niko1point0** [comment]
I tried to run Homebrew applications on Yuzu while using a public and open source homebrew toolchain

https://github.com/switchbrew/switch-examples/blob/master/graphics/opengl/textured_cube/source/main.cpp

When I ran this sample, the cube was spinning at super high speeds. However, on a physical console, the cube spins much slower. Please fix this bug

**Comment by niko1point0** [comment]
The reason for this, @Hexagon12 @legoj15 @imxieyi, is because the Switch function armGetSystemTick() is not properly implemented.

**Comment by legend800** [comment]
Just noting this impacts Ultra Street Fighter 2 too. When navigating the all the game's menus, the selection cursor moves ~5 spots instead of 1. You have to go up and down repeatedly until you randomly land on where you're trying to go. Same with dpad and analog stick. No setting seems to impact this at all.

Originally logged here:  https://github.com/yuzu-emu/yuzu/issues/2102

**Comment by niko1point0** [comment]
In the Ryujinx emulator, armGetSystemTick() is properly implemented, and bugs related to this glitch should work in Ryujinx.

However, Ryujinx fails to do literally everything else. In my experience, Ryujinx fails to read romfs and fails to draw any textures, but it does implement armGetSystemTick() correctly

**Comment by niko1point0** [comment]
If there is anything else I can do to be helpful. Let me know

**Comment by legoj15** [comment]
So an update from my end: Pokémon Quest seems to have speed up issues too (up to twice the speed in the camp, overworld & ingame), and thanks to some canary improvements, I can play Kirby Star Allies fast enough to see that that game runs at double speed everywhere (but music is unaffected in both games). Fast RMX has sped up music in the menu but I'm not 100% sure if it's related because I can't emulate the game fast enough beyond the main menu to see for myself.

**Comment by niko1point0** [comment]
There is another reason why this bug might be happening. Not only is armGetSystemTick() not properly implemented, but also time() is not properly implemented. 

The command time(null) is supposed to get the time of the system, such as time of day and date. Please look at this homebrew demo:

https://github.com/switchbrew/switch-examples/blob/master/time/source/main.c

On the first frame of the demo, the time is 100% correct, but then the clock moves extremely quickly in Yuzu, even though the clock is normal on the original Nintendo Switch hardware. Could the problem be related to how the system clock is emulated?

**Comment by Narugakuruga** [comment]
I test Detention, a Unity game. It used to run too fast but in canary 1224 the game runs at normal speed.

**Comment by legoj15** [comment]
Can concur; Kirby Star Allies now runs at the proper speed on the latest canary

**Comment by imxieyi** [comment]
Tried those games again and this issue has already been fixed.

**Comment by Narugakuruga** [comment]
Test Ultra Street Fighter 2, ran at normal speed.
