### ISSUE TITLE
Ubuntu 18.04 LTS [make error on yuzu-canary]

### ISSUE THREAD

**Issue by Dorzalty** [yuzu-emu/yuzu#1993]
Hello,

I'm trying to build yuzu-canary for Ubuntu, using AMD hardware if it matters (I've got Padoka), and I'm having an error on the make step. I've attached the error presented to me in the terminal to the post as a pastebin (so as to not make this post a huge scroll problem).

https://pastebin.com/1ny8VU3Y

Several days ago I managed to build the nightly version just fine after feeding the system its dependencies. I'm not sure what to make of this error at all. Is this on my end, or something else entirely?

Thanks for reading,

**Comment by Hexagon12** [comment]
Please report this under the appropriate PR (#1959) if it's not merged to master, thanks.

**Comment by legoj15** [comment]
It is related, your compile error has to do with chrono & time and that linked pull request is what is causing your error, since master (Nightly) doesn't have anything like that and I'm pretty sure that's the only time related code in Canary
https://github.com/yuzu-emu/yuzu/blob/ee0f5638c086ebfadd87adbdbed7c057f535cf48/src/yuzu/configuration/config.cpp#L662-L664

**Comment by Dorzalty** [comment]
Okay, thank you for the information legoj15. I don't know what to make of the emulation information, and saw the time stuff and just thought maybe I was just supposed to use a similar tag used in that link. lol 

I'm guessing I'm supposed to post my information in the thread or link back to this thread in it, but it seems like it was already done or otherwise I'm not sure how to go about it, but either way, thank you for the above.
