### ISSUE TITLE
Stubbed function causes Unicorn fallback?

### ISSUE THREAD

**Issue by NWPlayer123** [yuzu-emu/yuzu#2009]
Figure this might be useful to post
- Canary 1810
- trying to run https://www.nintendo.com/games/detail/boom-ball-boost-edition-switch
- it's Unity so obviously doesn't boot
- look at the logs and apparently an unimplemented function causes Unicorn to run the same instruction over and over.

`Core.ARM <Info> core\arm\dynarmic\arm_dynarmic.cpp:InterpreterFallback:65: Unicorn fallback @ 0x8A5B62C for 1 instructions (instr = E7FFDEFE)`

Full log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2737868/yuzu_log.txt)

<meta name="titleids"  content="01009FA00A570000">

**Comment by Hexagon12** [comment]
Which function exactly did you try to stub? I don't see anything that is new immediately in the logs.

If you haven't stubbed anything yourself, then this could point to more serious issues, since this ARM  instruction is essentialy a breakpoint / UDF. One possible reason may be a badly stubbed service command, so I would request you to get me a log file with the log filter set as `*:Debug` in Emulation - Configure - Debug.

**Comment by NWPlayer123** [comment]
I didn't stub anything, I'm saying all the stuff that is currently stubbed that's in the log. Here's a better one as asked @Hexagon12 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2747274/yuzu_log.txt)

**Comment by Hexagon12** [comment]
Does the game still not work?

**Comment by bukyapavankumar** [comment]
happens in gear of unlimited 2 
Core.ARM core\arm\dynarmic\arm_dynarmic_64.cpp:InterpreterFallback:70: Unicorn fallback @ 0xA170A34 for 1 instructions (instr = E7FFDEFE)

**Comment by choppymaster** [comment]
Now occurs? Unicorn function removed nah?

**Comment by bukyapavankumar** [comment]
Didn't check

**Comment by german77** [comment]
Works fine on latest mainline
