### ISSUE TITLE
Windows MSVC Package really bigger since Canary 1790 (Around 4x more)

### ISSUE THREAD

**Issue by superheri** [yuzu-emu/yuzu#2013]
Between Canary 1788 and 1790 the size of Windows msvc package grew up from around 17 MB to 64 MB as told from yuzu installer. 

Is there a reason for this? 

It seems to me that there is something that is now included in the package that wasn't before that is maybe unintended since the other version of yuzu (for linux or mingw) did not saw size changes that big. 

For users with limited network, it might be a problem to have to download around 4 times more data than before.

**Comment by BSoDGamingYT** [comment]
The QT applet and its dependencies are now included, that explains the size increase

**Comment by superheri** [comment]
But why only for one version of the build?

**Comment by FearlessTobi** [comment]
It's caused by the added QWebEngine dependency, which is used to render SMOs game manual for example. I'm not sure if size can be cut from it - that would be a question for @DarkLordZach.

**Comment by DarkLordZach** [comment]
@FearlessTobi Unfortunately I have already removed as many things as I possibly can, most of the space is a single dll for the core web engine stuff. Unfortunately, even if something else could be remove it would a few MB at most.
@superheri The issue is known and is not an issue. Additionally, these are only packaged with MSVC as only MSVC supports QtWebEngine. As mingw doesnt, it doesnt include the deps. If you are really constrained and absolutely cannot use the 64MB version, then use the MinGW version.
