### ISSUE TITLE
Please, do not use Nintendo and Switch names in the emulator

### ISSUE THREAD

**Issue by CptFoda-se** [yuzu-emu/yuzu#2039]
Hello. 

This is not a "issue", it´s more like a advice.

I seen a image of the shaders screen loading that will be released soon (I think), and in the image we can see the logo of Nintendo and Switch.

Hey, it´s cool, OK. But we all know that the emulator should not use brands and names that is copyrighted. 

This can be let you guys in some trouble. Please fix this.

Put "Yuzu" instead of Switch, and remove the Nintendo logo.

Bye.

**Comment by DarkLordZach** [comment]
No, we cannot get in trouble for this. The images shows (the nintendo logo and nintendo switch gif) are from the game itself. I don't know if you have tried that PR with homebrew, but the images won't appear because homebrew doesnt have them. What you are saying is akin to yuzu not being able to show game content because it's copyrighted, which is absurd. Since we do not actually distribute these images, we shouldn't be in any trouble.

*DISCLAIMER: Not a lawyer, this is not legal advice*

Requesting to close as unnecessary.

**Comment by jroweboy** [comment]
This is not an issue as it's data directly pulled from the games headers. We do not package these images into yuzu. As such there should be no legal issue as we are simply emulating the loading screen as it works on the switch.

**Comment by CptFoda-se** [comment]
thanks, I did not realized that was from the game itself.
