### ISSUE TITLE
Request: Better compression for the Release

### ISSUE THREAD

**Issue by Ghostotakoi** [yuzu-emu/yuzu#2213]
Please compress the canary and nightly using 7-zip ultra preset, it will highly increase the compression rate of all the release, some times reducing size in half... Example this release is 60mb and i compressed in 7-zip ultra preset an it reduce to 38mb.

**Comment by ExsertWizard** [comment]
The compression algorithm and format used is determined by the automated Appveyor builds. It is beyond my scope if its possible to change the the compression format and algorithm from the CI itself.

**Comment by jroweboy** [comment]
@ExsertWizard its not. https://github.com/yuzu-emu/yuzu/blob/master/appveyor.yml#L151 and https://github.com/yuzu-emu/yuzu/blob/master/appveyor.yml#L101

**Comment by Ghostotakoi** [comment]
@ExsertWizard rpcs3 has 7zip compression, also citra.

**Comment by ExsertWizard** [comment]
@Ghostotakoi well then i'm not sure why it still compresses as zip even though it has been set as 7z as default. At the moment, you have no choice but to patiently wait until it finishes downloading or get better internet.

**Comment by Ghostotakoi** [comment]
Is this possible @lioncash ???

**Comment by MerryMage** [comment]
The canary repository has 7z releases here: https://github.com/yuzu-emu/yuzu-canary/releases

**Comment by neico** [comment]
Not for msvc, which is what is being used via the updater on windows

Which is pretty much what this issue report is about,  
as you can observe with the mingw archives how greatly they vary in size depending on the format used.

**Comment by DarkLordZach** [comment]
The issue is simply that compressing the msvc releases with 7z would require users to have 7zip installed, which would add complexity and difficulty to our install process. Therefore, I am strongly against any change to the installer as it is now. This is kindof similar to how we didn't add the ability to change the installation directory. Put simply, options add complexity. We want our installer to work for the masses, not for the edge cases.

@Ghostotakoi Should you desire, we could look into compressing msvc builds as both 7z and zip (akin to mingw), but that's it. 7z compressing for the installer is just not something we can do.

Requesting to close.

**Comment by Ghostotakoi** [comment]
@DarkLordZac that would be really nice to have the option to do choose if you want to download a 7zip or a zip, like in citra releases.

**Comment by Ghostotakoi** [comment]
I am reopening this request because it still have not been done, i just want an alternative .7z option for the msvc version.
