### ISSUE TITLE
Suggestion for memory.h / memory.cpp

### ISSUE THREAD

**Issue by Sam-Belliveau** [yuzu-emu/yuzu#2290]
In the function ReadCString, you return a std::string, which I feel is a bit overkill. The max size variable might not convey the right message. I would suggest a std::string_view or a classic char*. Im new to this project so I would love some insight to this decision.

**Comment by lioncash** [comment]
In most cases, actually owning the data is preferable to a view, especially when later on when other facilities are more thoroughly implemented (particularly ports require storing the port name). Using a view is generally undesirable, since the pointed to memory can change at any time over the course of the emulated software's lifetime. We also don't strictly have control over what software does in emulated memory.

A view is a good idea when one can know with absolute certainty that the string data will live throughout the use of said view. This makes it unsuitable in this case, given we can't make guarantees about things in memory other than at the immediate point of retrieving and storing them.

`std::string` itself is generally not terrible either, every major provider (that we care about) for the standard library implements short-string optimizations for std::string, so it won't actually heap allocate unless std::string is larger than an implementation-specific amount of characters (with MSVC's STL and GCC's libstc++, this is 16 characters, with Clang/libc++ it's 22 characters).

**Comment by Sam-Belliveau** [comment]
yea sorry, I was tired when I wrote this, so I overlooked some things. Such as the fact that memory may not be concurrent, or things like ownership. While I am here, I might as well suggest some things that are not important. You may not need to shrink the string as it may slow down usage due to deallocations. You may also want to calculate the size beforehand, by running through the memory beforehand, see how far away the '\0' is, and then reserve.

`

std::string ReadCString(VAddr vaddr, std::size_t max_length) {
    std::string string;
    std::size_t length;
    for (length = 0; 
         Read8(vaddr + length) != '\0' 
         && length < max_length; 
         ++length) {}

    string.reserve(length);

    for (std::size_t i = 0; i < max_length; ++i) {
            char c = Read8(vaddr);
            if (c == '\0')
                break;
            string.push_back(c);
            ++vaddr;
    }

    return string;
}
`

**Comment by Sam-Belliveau** [comment]
this might be slower if memory reads are slow

**Comment by ReinUsesLisp** [comment]
What's the state of this issue?

**Comment by ReinUsesLisp** [comment]
`ReadCString` is in a state where we pay for what we want.

Closing.
