### ISSUE TITLE
C++ error on older canary builds and all games crash on canary 2141

### ISSUE THREAD

**Issue by KCcomics123** [yuzu-emu/yuzu#2367]
On canary 2141, all games crash and if I try to use a previous canary build, it gives me a c++ error and i also can't report compatibility because there is no tab for that! I don't know what to do! On april 7, 2019, canary 2128 worked perfectly but I updated yuzu to 2141 and all this started!

**Comment by Yvar192** [comment]
try giving some more debugging information. See what exact version broke it, provide logs, tell what the actual "c++ error" is, ect. Devs can't really do much with this

**Comment by Hexagon12** [comment]
This is a bug tracker for developers and not a support forum. Please ask on the yuzu Discord or the Citra forum instead.

**Comment by fluffapparition** [comment]
@Hexagon12 I request that we re-open this, it is a bug report so it belongs here. He made it clear that a specific canary build was broken and that there was an exception/error of some sort. 

From what I understand this is certainly the build itself, and I can't see any other possibility, without context suggesting otherwise.

@KCcomics123 Please screenshot the error and place it here. I'm not as adept with C++ as most of the others around here but I know a few other .NET languages and have some personal debugging experience, on top of that there's plenty of devs willing to take a look. Without seeing it for ourselves though we can't identify the problem.
