### ISSUE TITLE
AMD Switchable Graphics Not Working Properly

### ISSUE THREAD

**Issue by Crackz66** [yuzu-emu/yuzu#2385]
I'm getting the error in the screenshot below everytime I want to load anything in Yuzu. After checked by myself and then with the help of some nice people from Yuzu's Discord , I found out that my AMD GPU is compatible with Open GL 4.4 (Yuzu asking for 4.3) , but the error continued to show up even if I forced it to run on High Perfomance from the AMD Control Panel.
Other fixes I tried was to update the drivers , perfoming a clean uninstall then reinstalling the AMD Driver, but nothing seems to work.
Like someone from Discord pointed out , this problem seems to be common with Intel 3000/4000 cards which run along AMD . It happened to me in some other games , like GTA V , and the final conclusion was that like GTA V ,  Yuzu still uses INTEL GPU . Usually for big games like that I found a fix after some days of searching, but cannot find a resolve for YUZU.

Is worth mentioning that on same Laptop I'm running Citra with near flawless perfomance , this shows that Citra uses the right GPU, because the  Intel one won't be able to run it to playable speeds.

SPECS: 
- Windows 10
- Intel i5 2430m
- 6GB RAM
- AMD Radeon HD 6470M + Intel HD 3000

YUZU Version: Canary 2157
LOG: Empty

Error image:
![image](https://user-images.githubusercontent.com/49500121/55917735-25c28480-5bf9-11e9-9808-ac7bf34c54b3.png)

If you need aditional info , you can ask me for it. Thank you in advance.

**Comment by mineas312** [comment]
Please, make sure using that application that GPU can use OpenGL 4.3 Core.
http://realtech-vr.com/admin/glview
![gl](https://user-images.githubusercontent.com/17180405/55921626-d3379700-5bfd-11e9-9146-c484dadb912e.png)

**Comment by fluffapparition** [comment]
Pretty self-explanatory-- either upgrade your hardware or fix your drivers.

That being said, I know from personal experience that Windows 10 is absolutely terrible at picking the right drivers for older or lower end "Intel HD Graphics" integrated GPUs. If you initially got the computer with an OS older than Windows 10 installed, chances are that the Windows 10 setup replaced your perfectly working driver with one that is slightly more outdated. Go ahead and try to find your manufacturer's drivers they put on the system when it was first purchased, or temporarily switch over to a Windows 7/8.1 installation if you want and try seeing if it works there. OpenGL is not natively supported by Windows (hence why OpenGL and Vullan are faster on Linux). Therefore, in order for OGL/Vulkan APIs to work they must be installed into the driver in some fashion since Windows only works with DirectX. If the driver is not configured properly to run those APIs then the PC will think the GPU can't support it.

If this doesnt solve your problem, that probably means your GPU is simply not compatible. If this is the case, you should either upgrade the video device (probably the entire CPU too, since that's where integrated graphics are embedded) or buy a newer PC with a compatible GPU.

I hope this explains the error and that you manage to get YuZu working. Feel free to ask any questions. :smiley:

**Comment by Crackz66** [comment]
In my post I said that already I reinstalled the latest compatible driver from the AMD website (Catalyst 15.7.x) , after did a clean unistall. 
So probably is just the driver support, cause yuzu is forced for the amd gpu. Sadly can't upgrade it because ..obviously is a Laptop...and everything is glued up.

**Comment by legoj15** [comment]
You can specify which GPU a program uses on a laptop on windows 10; Go to settings, System Settings, Display, and in small text there is something that says "Graphics settings" click it, and you'll see this screen
![image](https://user-images.githubusercontent.com/7399802/55982389-d1ee8480-5c66-11e9-968e-df1cfc35757f.png)
As you can see, I have Dolphin as an example. Browse for yuzu.exe and after adding it, click Options under yuzu.exe, and change it to "High performance"

**Comment by Crackz66** [comment]
@legoj15 , I already did this, no results.

**Comment by legoj15** [comment]
All I can say is that due to the age of your hardware, it is very likely that your GPU supports *some* OGL 4.3/4.4 features, but not the ones that yuzu specifically require. AMD and NVidia like to list their GPU OpenGL compliance as the highest they possibly can without techically lying; so AMD *might be* listing your GPU as supporting 4.4 when in actuality it doesn't support all the features of 4.3/4.4 (this has happened to me with a NVidia GTX 660)

Also, Citra doesn't require the same features that yuzu does so that is why your GPU works fine there; apples to oranges comparison

**Comment by Crackz66** [comment]
@legoj15 Being released before OpenGL 4.3 is not a problem, because I managed to run yuzu on a pc with a HD 5870 , released in 2011 as well.

Also I think is just AMD listing their gpu with higher features.
Whatever , thank you all for help . I'll close the issuse , and if this is really an Yuzu issuse, it will be resolved some other time.

**Comment by suerion** [comment]
Hello, the same thing is here with AMD Radeon HD 6700 Series, in the database, there is OpenGl 4.4, 

But with switchable Intel 3000 is the yuzu not work.

HP Pavilion dv7-6c82eg
![grafik](https://user-images.githubusercontent.com/55131959/82130236-d5d5ca00-97c9-11ea-8599-9e0b046eef68.png)

**Comment by goldenx86** [comment]
Yuzu is not compatible with any Terascale GPU.
