### ISSUE TITLE
Missing HLE service command 'GetQuestFlag' in 'set'

### ISSUE THREAD

**Issue by DarkLordZach** [yuzu-emu/yuzu#2615]
Needed by Capcom Beat'em'up

<meta name="titleids"  content="01005D200B530000,010094E00B52E000">

**Comment by ogniK5377** [comment]
This is very trivial to implement. GetQuestFlag simply checks if a console is a kiosk console or not. Retail consoles will always return false however we can lock this behind a config since it seems games check for it. Some users might want to see how a game differs from retail mode and kiosk mode. A few applications also check for this flag, eg qlaunch.
