### ISSUE TITLE
Audio: Volume Clamps to Maximum on Windows

### ISSUE THREAD

**Issue by anodium** [yuzu-emu/yuzu#2935]
On starting a game, the volume will max out unconditionally. This is suspected to be an upstream issue for `cubeb`, but hasn't been tested.

Steps to reproduce (Courtesy of @chris062689):

1. Start a game, ears bleed.
2. Lower the volume using the Windows volume mixer.
3. Enjoy the game at reasonable volume. Close the game.
4. On the next launch, start the game again, ears bleed.

I'll be doing regression testing on multiple versions of Yuzu and Windows. Will also test if it's reproducible under Linux or macOS, and if other `cubeb` dependent projects (Dolphin, Firefox, Citra, etc.) have similar issues.

**Comment by fluffapparition** [comment]
Probably audio backend issues, considering this wasnt intended i dont see how we would have implemented this ourselves.

Personally I haven't had these issues when using Citra and Dolphin, although i normally prefer XAudio2 when using dolphin. Citra on the other hand i normally use Cubeb with and it works fine.

If i had a copy of my switch firmware files i would test to see if this problem happens under my configuration as well, but unfortunately i dont own a homebrew enabled switch since mine was released after all of the hardware patches.

**Comment by vitor-k** [comment]
From testing with Citra, this also happens when using cubeb, but not sdl2.

It's also not exactly as extreme as the description makes it seem.
The default for a windows application is to use the same volume as the general volume (basically the max allowed), and this can be changed in the audio mixer, with these settings persisting between sessions for most applications.
But apparently this doesn't happen when Cubeb is used, which makes the volume go to the maximum allowed volume, and being unmuted.
