### ISSUE TITLE
Missing HLE service command 'SetOperationMode' in 'ISystemLocalCommunicationService' (ldn:s)

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3119]
[ 787.647844] Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:154: Assertion Failed! Unknown / unimplemented function 'SetOperationMode': port='IUserLocalCommunicationService' cmd_buf={[0]=0x6, [1]=0x8000000C, [2]=0x1, [3]=0x22858A, [4]=0x4F434653, [5]=0x0, [6]=0x0, [7]=0x0, [8]=0x49434653}
[ 787.647856] Debug <Critical> core\hle\kernel\hle_ipc.cpp:ParseCommandBuffer:163: Assertion Failed!
[ 787.647861] Debug <Critical> core\hle\kernel\hle_ipc.cpp:WriteToOutgoingCommandBuffer:234: Assertion Failed! Handle descriptor bit set but no handles to translate
[ 787.647871] Debug <Critical> core\hle\kernel\hle_ipc.cpp:WriteToOutgoingCommandBuffer:239: Assertion Failed! Sending PID is not implemented

required by pokemon sword and shield

tested in yuzu 60

<meta name="titleids"  content="0100ABF008968000,01008DB008C2C000">

**Comment by JonasZ95** [comment]
I tried to stub multiple functions for IUserLocalCommunicationService. First I don't think It's called SetOperationMode(402) It seems to be alternative initialization function because It always calls 401 at the beginning or after something fails and Finalize(401) was called, ldn_mitm also calls It InitializeSystem2. However, If you stub system functions with result api codes and correct dummy data structures(as connected to a network) It seems the switch tries to call bind to listen on a socket which is also not implemented which turns this into a problem how to implement networking.

It seems Pokemon Sword/Shield constantly tries to initialize this service and retries If It fails to do so. I think the best option to fix this is to log how the service(?) behave while airplane mode is enabled. However, I don't have a switch which supports homebrew right now, so I cann't really do this.

**Comment by callmenemo491** [comment]
@Hexagon12 , i think we can close this ticket, as PR merged...
