### ISSUE TITLE
Log when the game (tries to) load a file

### ISSUE THREAD

**Issue by mariomadproductions** [yuzu-emu/yuzu#3133]
This would be a useful feature for debugging, datamining, game modding. Desmume, Dolphin and Cemu have similar features.

**Comment by DarkLordZach** [comment]
With the way VFS is currently implemented, this would have a severe performance deficit.
However, something similar may be in the works at this time.

**Comment by sharkiller** [comment]
performance drop should not be an issue. this is not a feature to have enabled by default.

**Comment by DarkLordZach** [comment]
I am afraid you misunderstand. With how the VFS works and how games read files this will cause performance impacts.

**Comment by fluffapparition** [comment]
@DarkLordZach 

Sharkiller is saying that even if it causes performance issues, it's not a feature that everyone is using anyway, it's just an optional feature and being able to closely investigate the in's and out's is worth a temporary performance drop anyway.

For example, nobody likes software rendering because it's incredibly inefficient and runs terribly, but to some it can be handy for specific reasons.

**Comment by german77** [comment]
Files are logged if you set logging to debug.` Service.FS:Debug ` if you wish to log only filesystem calls
