### ISSUE TITLE
[Feature Request] Add Support for Homebrew compatible NSP/XCI compressor/decompressor NSZ, XCZ, NCZ

### ISSUE THREAD

**Issue by goedzo** [yuzu-emu/yuzu#3245]
As Homebrew NSP and XCI files get larger and larger, compression support is a welcome feature to be included in Yuzu. The code is already implemented here: https://github.com/nicoboss/nsz so I am hoping this feature could be included and implemented in Yuzu as well.

As I could not find any feature request for NSZ or XCZ feel free to review this , or close the issue if it is not going to be supported. I can understand any reasoning that argues for or against it, so please let this issue be a way to communicate the official Yuzu answer for this feature request.

**Comment by ogniK5377** [comment]
We're dedicated to emulating the Nintendo Switch System, these formats(NSZ, XCZ, NCZ) do not officially exist on the system. They have not been thoroughly tested and have quite a bit of issues with them, because of this we won't be seeking to add support of these extensions.

**Comment by eadmaster** [comment]
is there any alternative compression format currently supported?

**Comment by nickkeane** [comment]
Will support ever be added for NSZ (or any other compression) at some point when it's more stable?

**Comment by woolrage** [comment]
ogniK5377, it is very sad that you think supporting compressed dumps of your licensed games is not worth it, only because Nintendo did not think of creating such format an its own, forcing people to download loads of GB uncompressed stuff from its servers when buying games from eshop or even when downloading updates. 
If you look at sizes of some games, I think it is obvious almost everyone would like to reduce the storage needed.
I would really appreciate NSZ and XCZ support!

**Comment by bajolzas** [comment]
Most mature emulators support some kind of compressed game support. In the case of NSZ even an actual jailbroken switch supports it.
I can understand not implementing a feature in the near future because there are more important stuff that needs to be worked on.
But right away closing an issue just because what is being asked does "not officially exist on the system"?!
Isn't the point of emulators (other than preservation) being able to improve on the experience offered officially?

**Comment by tastyratz** [comment]
I understand NSZ wasn't a priority earlier on, but, as yuzu has matured I'm wondering if this could be re-evaluated?
With the existence of tools like NSC builder, the ability to repack your nsp's with updates could go a long way if we could compress the backups for less space. This seems like it has a very legitimate use case for authentic backups.

I'm not familiar with what problems exist for these compression formats that get in the way here and I'm not finding. anything with searches.

Is this a philosophical close or a technical one?
