### ISSUE TITLE
Hatsune Miku Project DIVA MEGA39s - Broken Rendering

### ISSUE THREAD

**Issue by slashiee** [yuzu-emu/yuzu#3406]
Any rendered in-game graphics are heavily broken.

yuzu mainline 163

GeForce RTX 2080
Ryzen R9 3900X

Emulator:
![image](https://user-images.githubusercontent.com/15317421/74382859-fb0a0500-4da2-11ea-8b8e-2672a045bddf.png)

Console:

![image](https://user-images.githubusercontent.com/15317421/74382890-065d3080-4da3-11ea-818e-426d1858e182.png)

Log:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4195320/yuzu_log.zip)

**Comment by Yukikami39** [comment]
Adding more details using Yuzu EA 206:
- Everything 2D displays perfectly.
- Shadows are not correct.
- Character meshes randomly appear and disappear depending on the view, which could be a cause of the spammed:
"Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:146: API ERROR 1286: GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.
Debug <Critical> video_core\renderer_opengl\gl_rasterizer.cpp:Clear:472: Assertion Failed! Tried to clear Z but buffer is not enabled!"

![yuzu_pflYCJlPnW](https://user-images.githubusercontent.com/13494982/74596345-bc03da00-5056-11ea-8745-c469c819370b.png)
![Discord_Gw59dE911O](https://user-images.githubusercontent.com/13494982/74596348-c7ef9c00-5056-11ea-823c-194aaafdf084.png)
![yuzu_VYNnVwKShU](https://user-images.githubusercontent.com/13494982/74596360-e81f5b00-5056-11ea-987c-d0d75cc47057.png)
![yuzu_no7CZ6K1ZL](https://user-images.githubusercontent.com/13494982/74596317-45ff7300-5056-11ea-989b-3ef4dfd4b4c9.png)
![yuzu_GsSUa8hnry](https://user-images.githubusercontent.com/13494982/74596319-4d268100-5056-11ea-8f03-9c732ea359d9.png)

- Characters leave a trail of black which covers the screen (could also be of the same message above)

![yuzu_b5qIUi2db8](https://user-images.githubusercontent.com/13494982/74596355-dc339900-5056-11ea-8191-e9dce525db56.png)

- Audio is messed up. Sounds like buttons are fine, but once pressed, they play once then loop endlessly. No music audio plays. Music format is .ogg at 44100 Hz. If a skip is used for intros, main menu will have music which sounds like it's been compressed to the max.
- Movies (which are in .mp4 format) don't play at all.

**Comment by slashiee** [comment]
Audio is a separate issue, movies are related to #2643

**Comment by Yukikami39** [comment]
I see. Also i have only -ui_ps4 enabled in the screenshots, which don't effect 3D graphics. I have tried -no_npr enabled/disabled, but it looks the same, because everything looks like it's under a shadow.

**Comment by nevespt** [comment]
Also the game don't boot in **`Vulkan API`**

**Comment by nastys** [comment]
@Yukikami39 48000 Hz, actually.

**Comment by randompasser** [comment]
Main menu background no longer renders correctly as of Early Access 263
![regression1](https://user-images.githubusercontent.com/33059426/76480937-0a16be00-6408-11ea-8320-c30b643bea45.png)
![regression2](https://user-images.githubusercontent.com/33059426/76480940-0aaf5480-6408-11ea-9cd8-c8618aab5c50.png)

**Comment by slashiee** [comment]
PR #3529 fixes this issue

**Comment by Ghostotakoi** [comment]
@slashiee yeah but audio still broken right??

**Comment by slashiee** [comment]
@Ghostotakoi Audio issues are separated: #3428 and #3449

**Comment by slashiee** [comment]
Fixed with #3542 being merged to master.
