### ISSUE TITLE
The Walking Dead: The Final Season using 100% GPU and stops responding/crashes

### ISSUE THREAD

**Issue by Morph1984** [yuzu-emu/yuzu#3522]
OpenGL
yuzu 7
![image](https://user-images.githubusercontent.com/39850852/76793747-fd91bd00-679b-11ea-8b8a-2ba87108764e.png)
[yuzu_log_MAINLINE_7.txt](https://github.com/yuzu-emu/yuzu/files/4340051/yuzu_log_MAINLINE_7.txt)

yuzu 197
![image](https://user-images.githubusercontent.com/39850852/76793765-03879e00-679c-11ea-948e-1c76fc00de77.png)
[yuzu_log_MAINLINE_197.txt](https://github.com/yuzu-emu/yuzu/files/4340053/yuzu_log_MAINLINE_197.txt)

yuzu 106
![image](https://user-images.githubusercontent.com/39850852/76794305-19499300-679d-11ea-9656-ed92e3376bc5.png)

yuzu 107
![image](https://user-images.githubusercontent.com/39850852/76794173-d5568e00-679c-11ea-85a5-6dc2573c9998.png)

Vulkan
yuzu 198 (Crashes)
[yuzu_log_MAINLINE_198_VK.txt](https://github.com/yuzu-emu/yuzu/files/4340060/yuzu_log_MAINLINE_198_VK.txt)

Also, missing texture format 24 (G8R8)

**Comment by ToxaGaming** [comment]
Thought I'd add some more details to this issue. So first of all the main menu (the only part of the game that i tested) runs basically perfectly on yuzu 7 with full speed and no visible graphical issues (chose the earliest Mainline build i could find to see if the game ran fine before). 

Somewhere between Mainline 7 and 106 the bus in the screenshots disappeared due to an issue, but was later fixed in Mainline 107 and yuzu also had a much higher GPU usage in this game. 

And now comes the fun part, 'cause with Mainline 107 the GPU usage increased yet again to the point where it taxed my GPU 100% and the game ran at 4-5FPS from 60FPS as it did in Mainline 7 and in some build since 107 the GPU usage increased yet again to the point where it's unplayable with the emulator not responding and then either crashes by itself or has to manually be killed in Task Manager.

**Comment by ReinUsesLisp** [comment]
Maybe this should stay opened until the other issue is merged?

**Comment by ToxaGaming** [comment]
Which issue are you referring to? Both the crashes and the GPU usage was fixed as of PR 3839 (R8G8UI)

**Comment by ReinUsesLisp** [comment]
Ah, I might have ignored that part. I thought crashes were still happening. Closing.
