### ISSUE TITLE
Experiencing extremely intermittent crashes in Yuzu EA 334 when trying to launch Super Smash Bros. Ultimate.

### ISSUE THREAD

**Issue by Nelkerino** [yuzu-emu/yuzu#3618]
In Yuzu EA 334, when attempting to launch Super Smash Bros. Ultimate, I experience seemingly random crashes before the title screen even manages to come up.

Either Yuzu will crash at that instant, or it will run perfectly fine with no issues, it seems to occur entirely randomly, crash log attached.

GPU: RX 580
CPU: R5 2600
RAM: 16gb ~2900 mhz

**Comment by theboy181** [comment]
Vulkan?

**Comment by Nelkerino** [comment]
Aye, that it is.

**Comment by theboy181** [comment]
me too - started before this EA

**Comment by ReinUsesLisp** [comment]
Does it happen in mainline?

**Comment by Nelkerino** [comment]
crashed on first bootup with mainline, every launch afterwards has been fine.

**Comment by Nelkerino** [comment]
only just realized that i didn't even attach the crash log, my bad.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4442120/yuzu_log.txt)

**Comment by ReinUsesLisp** [comment]
Do you have any mods injected?

**Comment by theboy181** [comment]
Is ok in mainline and issues even with no mods.

**Comment by Nelkerino** [comment]
Zero mods installed, this occurs on a clean save too.

**Comment by theboy181** [comment]
Still happening on current EA for me.. What are your computer specs @Nelkerino ?
Im i9 9900ks 2080ti

**Comment by Nelkerino** [comment]
posted in op @theboy181

**Comment by theboy181** [comment]
opps - thanks.. I wonder if others are having issues?  have you tried reinstalling the driver?

**Comment by Nelkerino** [comment]
yeah according to the support team in the discord others are having issues as well, i'm just running on mainline to bypass rn.

**Comment by lat9nq** [comment]
In EA 339 I am experiencing the same issue (SSBU crashes immediately after the loading bar begins to disappear). It crashes every time, not sometimes.

Manjaro Linux 19.0.2, kernel 5.5.15-1-MANJARO
Ryzen 7 2700X
GTX 980 Ti running 440.82
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4452806/yuzu_log.txt)

The crash only happens when I boot SSBU using Vulkan, as other games can boot in Vulkan, and SSBU boots in OpenGL. I've tried renaming the nand directory and reinstalling SSBU from its XCI to no avail. Yuzu mainline seems to boot SSBU fine in Vulkan at time of writing, and EA 20200404-3abab807b works, too.

**Comment by FernandoS27** [comment]
We have confirmed the issue, We are investigating.

**Comment by FernandoS27** [comment]
The issue has been found, should be fixed next EA version.

**Comment by Nelkerino** [comment]
fantastico, glad to see it fixed so quickly, props to y'all on the team.
