### ISSUE TITLE
Project DIVA Mega Mix - Vulkan crashing after #3542

### ISSUE THREAD

**Issue by ActualMandM** [yuzu-emu/yuzu#3717]
yuzu Mainline 206

GeForce RTX 2080
Ryzen R9 3950X

Vulkan crashes during boot-up starting from [Mainline 206](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-206) and above. This is caused by #3542.

<img width="961" alt="2020-04-18_13-07-14" src="https://user-images.githubusercontent.com/15317421/79670184-03e9cf00-8176-11ea-9ebb-c91d5d8c5760.png">
<img width="961" alt="2020-04-18_13-07-41" src="https://user-images.githubusercontent.com/15317421/79670186-064c2900-8176-11ea-878c-cb88aaf7c99b.png">

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4497533/yuzu_log.zip)
[callstack.zip](https://github.com/yuzu-emu/yuzu/files/4497552/callstack.zip)

**Comment by slashiee** [comment]
Reverting the MME Shadow RAM changes in mainline 206 allows MEGA39s to boot under Vulkan once again.

**Comment by nevespt** [comment]
OpenGL dont boot

**Comment by slashiee** [comment]
Fixed with #4967/EA 1144
<img width="961" alt="2020-11-23_11-24-24_yuzu" src="https://user-images.githubusercontent.com/15317421/100008538-6d703280-2d82-11eb-8f9e-337fd4987313.png">
<img width="961" alt="2020-11-23_11-27-16_yuzu" src="https://user-images.githubusercontent.com/15317421/100008511-69441500-2d82-11eb-8814-764f5c5dc992.png">

**Comment by nevespt** [comment]
wich settings?

**Comment by slashiee** [comment]
> 
> 
> wich settings?

...early access and vulkan?
