### ISSUE TITLE
Support multichannel audio output

### ISSUE THREAD

**Issue by Dogway** [yuzu-emu/yuzu#3751]
I saw a ticket for downmixing but I would rather have all channels output as they are, so an option to don't downmix surround channels.

**Comment by FernandoS27** [comment]
Right now we'll focus on doing what the switch can do. Afterwards we'll see if we can add enhancements as Surround audio.

**Comment by legend800** [comment]
AFAIK the Switch support true 5.1 PCM, so I'm not sure if this would be an enhancement exactly. Maybe I don't understand. Here's a thread I found discussing the topic in-depth:  https://www.reddit.com/r/NintendoSwitch/comments/9ldpko/nintendo_switch_and_51_surround_sound/

**Comment by Dogway** [comment]
It's just a passthrough, channel in channel out. The same that's done for L and R but with the surround channels. It would be a required pre-step for the downmix feature, but no push here just a reminder, you guys are doing a great job.

**Comment by Edu2014** [comment]
does this have anything to do with being able to control the volume of the music, voice, effects within the game itself?

**Comment by ogniK5377** [comment]
I've experimented with upmixing mono and stereo to surround sound already. There are a few changes we need in our backend for it to actually work properly. As I've been told, our current build of cubeb doesn't actually support surround yet, it just downmixes to stereo. Once we get around to that then I can push out proper 6 channel support with upmixing

**Comment by Dogway** [comment]
Switch and many games support discrete 5.1 PCM channels so there shouldn't be a need to upmix (nor downmix) for such titles. Other ones with Dolby ProLogic II (is it still used?) should need upmixing though, but I'm really not concerned about those, UNLESS the cubeb is downmixing 5.1ch to DPLII and not to plain stereo, but it sounds hacky.

**Comment by ThreeDeeJay** [comment]
Any updates on this?
I don't know about Linux, but usually surround sound from apps/games gets downmixed to stereo by the Windows mixer, if that's the channel configuration used. Otherwise it can just 
So in my opinion, Yuzu should just implement surround sound first and let the system take care the downmix, if needed, and then implement a built-in downmixer.
And even better, Yuzu could implement [OpenAL (Soft)](https://github.com/kcat/openal-soft) like Dolphin which can take care of surround/downmix, even allow virtual surround for headphones without any external apps.

**Comment by pumpsomekins** [comment]
Is 5.1 available on Yuzu now?
