### ISSUE TITLE
Shinsekai Into the Depths reports various unimplemeted/stubbed services and bad API Performace calls

### ISSUE THREAD

**Issue by SilverBeamx** [yuzu-emu/yuzu#3779]
As the title says, Shinsekai into the Depths throws a plethora of API Performance calls in the log, alongside several calls to stubbed/unimplemented services and features. There might be something missing in our video core.

Performance is also quite bad, as it stays below 50% on my rig (8600k stock with a 1060 6gb).

Here are 2 logs of the issues:

[Shinsekai_log.zip](https://github.com/yuzu-emu/yuzu/files/4525578/Shinsekai_log.zip)
[Shinsekai_Debug_log.zip](https://github.com/yuzu-emu/yuzu/files/4525582/Shinsekai_Debug_log.zip)

**Comment by ReinUsesLisp** [comment]
Those logs in video_core are intended behaviour.
The buffer performance warnings are because the game is reading GPU memory from the CPU.
The texture format performance warnings are because Nvidia's driver is converting ASTC to another internal format.

If you want some of the missing features or services implemented, open an issue for them individually. This is too wide to be solved.
