### ISSUE TITLE
CPU utilization, Improve multithreading. GPU optimizations

### ISSUE THREAD

**Issue by chriskoups** [yuzu-emu/yuzu#3803]
Hey,

This is not an issue but more like a request.
I am building the application daily either from this repo or from EmulationChannel.

I have notice that the CPU it seems to be limited to 4 threads and that the GPU does not clock higher as it must do in 3D games despite that task manager reports the utilisation of 3D (I am using an NVIDIA 2080).

For the CPU, I found the part that refers to the Switch and its 4 cores.
Also found he two points were the systems cores are also reported as 4 cores.
Changing those values does not wield to more CPU utilisation!
Any particular reason for that?

For the GPU, I have seen the Fast GPU merge that happen few days ago but from my benchmark, does not have difference. Any more solid ideas on that is doing? Is it for low specification systems?

**Comment by EliEron** [comment]
Increasing the number of threads only helps performance if work is actually distributed to them. Since Switch games are coded to at most split their work between 4 threads adding more threads is entirely pointless. The additional threads will never be assigned any work. And that is not something the emulator can easily change.

The "Fast GPU" option does not actually affect the GPU performance at all. What it does is trick the game into thinking that GPU operations completed faster than they really did, by reporting a timespan that has been divided by 256. The point of doing that is that it reduces the likelihood that the game is going to reduce its resolution, as that is something many switch games are programmed to do when they detect that they are running to slow.

**Comment by theboy181** [comment]
👍

**Comment by chriskoups** [comment]
Thank you for the clarifications!
So, where do we have to focus to accelerate the performance? In execution acceleration? As far as I can see from my PC, nothing is more than 30% of utilization and games like Zelda Breath of Wild cannot have 30fps stable.

By using cpu screening in c++ I can see that GPU functions are capping the performance.
This function consume 30% of the processing speed: DmaPusher::DispatchCalls()

Anw, I just started working on it. I may need some time to understand how emulators work...... :/

**Comment by SilverBeamx** [comment]
The GPU is hardly the bottleneck. Emulation in yuzu is primarily CPU-bound, being that the entire Switch CPU is emulated on a single host thread/core (apart from a second thread with Async GPU enabled). A major update codenamed Prometheus is expected to solve this issue, with an ETA of a couple of weeks if everything goes according to schedule, as far as i know. 

Also, Github issues are generally used for problems/bugs within the emu. Discord would be a much more appropriate place to ask these things :)

**Comment by chriskoups** [comment]
I am looking forward to Prometheus showing up!

Discord is not for early access members?

**Comment by chriskoups** [comment]
Sorry for reopening the issue.
After I joined the discord channel, I find it unfriendly and with no options to communicate with anyone. They are 3 topics from which 2 are locked and one is the read me!

**Comment by ExsertWizard** [comment]
As stated by SilverBeamx, this place is for issue trackers of the emulator for developers, and therefore this discussion is better suited in the Discord server. Please read the server rules carefully to gain access to the rest of the channels (or as what you called it, “topics”).

**Comment by chriskoups** [comment]
-.- I have not read the last two lines as the emoticons got my attention. Thanks, closing it now.
