### ISSUE TITLE
Fullscreen, pop-up windows open in background

### ISSUE THREAD

**Issue by superheri** [yuzu-emu/yuzu#3903]
When playing in fullscreen mode the pop-up asking us to enter some text loads in background and we need to leave the fullscreen mode to make it work.

For exemple, in Pokémon Sword, next to the Pokémon center of the first city, a girl asks you your birth date and the pop-up is not visible in Fullscreen even though it's loaded in background.

**Comment by EliEron** [comment]
I assume this is the same issue that affects RPCS3, if so it is an issue that only affects NVIDIA users and only when using OpenGL, Intel and AMD users are not affected. Vulkan users are not affected period, regardless of GPU vendor.

The lead graphics dev of RPCS3 looked into ways of solving the issue but concluded it was something out of their control, as he suspected it to be caused by the NVIDIA driver doing some optimizations to the fullscreen OpenGL window that gave the screen priority over any other window that tries to render over it.

**Comment by superheri** [comment]
I can confirm that in my case, I was using a Nvidia card with OpenGL. Haven't tested Vulcan or AMD, so I can't confirm if it limits to Nvidia and OpenGL.

**Comment by EliEron** [comment]
I can't test AMD or Intel either, but I can test Nvidia on both OpenGL and Vulkan. On OpenGL I experience the issue, on Vulkan I did not.

The easiest popup to trigger in Pokémon SwSh is the renaming dialogue. So if others want to test this just go to any Pokémon Center and speak to the name rater, choose a Pokemon you caught and you'll be given a prompt to rename it.
