### ISSUE TITLE
Unimplemented shadow convert format "ABGR8U"

### ISSUE THREAD

**Issue by Zeroksas** [yuzu-emu/yuzu#3974]
Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0

Game: Brigandine: The Legend of Runersia

**Comment by finnsuchara** [comment]
I have the same issue? Yuzu Early Access 1091 randomly crashes when it tries to compile certain textures. I'm running Hyrule Warriors Age of Calamity Demo (the demo just came out 3 days ago as of writing this so maybe that's why).

yuzu_log.txt: 

[ 227.296974] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:GetGraphicsPipeline:215: Compile 0xCD4B957ED21819DB
[ 227.310762] Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
[ 227.310770] Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
[ 227.310796] Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
[ 227.310799] Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
[ 227.310811] Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
[ 227.310813] Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
[ 227.310828] Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
[ 227.310830] Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
[ 227.310839] Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
[ 227.310840] Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
[ 229.597619] Render.Vulkan <Critical> video_core\renderer_vulkan\vk_device.cpp:ReportLoss:458: Device loss occured!

**Comment by liamwhite** [comment]
Comment with a yuzu log if this is still relevant, but it looks like this code has been completely refactored as of now.
