### ISSUE TITLE
FE3H crashes on battles using OpenGL

### ISSUE THREAD

**Issue by puneet1999** [yuzu-emu/yuzu#4038]
Fire emblem Three Houses crashes whenever you enter the battle map. It will sit there normally as everything is working then decide to flicker and end the process. I can confirm this issue happens from Yuzu EA 530-585, to the most current one. I have tested EA 513 and this issue does not occur but softlocks will occur at chapter end. Others have confirmed this issue occurring but might not know if its GPU dependent. Vulkan does not have these issues therefore may be in the opengl code. 

I have tested with all the options, whether using single core or multicore and checked the yuzu mainline. This problem only occurs currently in the Prometheus build but not sure what code breaks it. 

My testing ranged from using Chapter 1 battle map therefore other maps may not have these issues. 

I have provided my system specs, log file and a backtrace (Never done it before so let me know if its fine)

Let me know whether you need more information

[backtrace.txt](https://github.com/yuzu-emu/yuzu/files/4719353/backtrace.txt)

[DxDiag.txt](https://github.com/yuzu-emu/yuzu/files/4719405/DxDiag.txt)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4719398/yuzu_log.txt)

**Comment by pPkMnh4to8994h** [comment]
Same here.
GPU driver crashes, along with emulator, at the beginning of battle.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5073459/yuzu_log.txt)
[DxDiag.txt](https://github.com/yuzu-emu/yuzu/files/5073476/DxDiag.txt)

**Comment by Trickytbone** [comment]
I'm getting the same issue, I don't know what's wrong. I crashed at the prologue, but a reload solved that.

**Comment by dolfy2** [comment]
i have the same issue, not sure what's causing it but if anyone finds anything that could help let me know.

**Comment by luananogueira** [comment]
Try change to vulkan

**Comment by pirods** [comment]
I've managed to play the game and reach the final chapters with few random crashes, mostly at the battle preparation screen where sound would work and controls as well but video would not show (and the emulator would crash).

Usually this was easily fixed by reloading the emulator. Now I'm getting unavoidable crashes on the PAT II Ch. 17 Blood of the Eagle and Lion To War at Gronder battle. I'm using Vulkan and I tried to fiddle with all the settings I could.

Loading screen stops, I hear the "battle preparations" music, FPS drop to 0 and the emulator crashes.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6228760/yuzu_log.txt)

**Comment by luananogueira** [comment]
PAT II Ch. 17 is a problem really =(

Normaly I realod emulator and change API before battle, try alternate OpenGL and Vulkan.

I finished the game yesterday (black eagle route) using yuzu 562 (same used on fitgirl repack from super smash bros)

**Comment by pPkMnh4to8994h** [comment]
On recent versions of yuzu Vulkan seems to work pretty well, and better than OpenGL.
Results may vary tho, since AMD has better Vulkan support in their drivers, afaik.

> Usually this was easily fixed by reloading the emulator. Now I'm getting unavoidable crashes on the PAT II Ch. 17 Blood of the Eagle and Lion To War at Gronder battle. I'm using Vulkan and I tried to fiddle with all the settings I could.

Ch. 17 crash is an ancient problem in yuzu, probably since the very launch of the game. Use RyujiNX to boot into battle prep screen and save there, or use save editor (guide available here - [https://www.reddit.com/r/yuzu/comments/e19gk5/guide_to_troubleshooting_pretty_much_everything/](url))
Look for "unavoidable crashes" section for instructions. It worked brilliantly for me.
