### ISSUE TITLE
[EA 650] Super Smash Bros Ultimate 99% GPU usage on main menu with Opengl with latest NVIDIA drivers 451.48 

### ISSUE THREAD

**Issue by IDSG** [yuzu-emu/yuzu#4155]
On the latest NVIDIA drivers (451.48) using a gtx 1070 and yuzu EA 650, the main menu causes 99% gpu usage leading to bad performance, when entering in smash battle works at full speed, selecting fighers and start a battle works fine too, but sometimes crashes after a while, previously i was using the 451.22 drivers and everything was working fine

**Comment by goldenx86** [comment]
With the same driver and a GT 1030 I get a 40% of GPU use in the menu.
Check for overheating or low clock speeds.

**Comment by puneet1999** [comment]
Tested on Nvidia gtx 970 and i get the 99%-100% gpu usage issue. Its an issue with the driver and OpenGL which is pretty common since its been conflicting with yuzu's code recently. I've tested with vulkan and i get 14% gpu usage.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4829038/yuzu_log.txt)

**Comment by IDSG** [comment]
> 
> 
> With the same driver and a GT 1030 I get a 40% of GPU use in the menu.
> Check for overheating or low clock speeds.

Everything it's working fine, no overheating and setting maximun perfomance on nvidia panel to avoid low clocks, i played about 1 hour without problems, so the only problem is the main menu

**Comment by MaoSetzer** [comment]
Same issue with the latest NVIDIA's driver but on SMO. I got terrible performance (15fps) with high gpu usage like on CAP Kingdom. It seems due to some effect. I have the Accuracy level set on HIGH, but when I set back to normal, 60fps rock solid! Never had this issue before driver update even on accuarcy level set on high.

**Comment by IDSG** [comment]
Here's the log, this is using EA 657

[Uploading yuzu_log.txt…]()

**Comment by Myoko** [comment]
btw botw crash everytime for 451.48! cannot start game

**Comment by choppymaster** [comment]
Does this occur now?

**Comment by IDSG** [comment]
> 
> 
> Does this occur now?

It's working better, the GPU usage still higher than rest of gameplay (more than 80% on that menu screen and less than 70% on a 8 players battle )

**Comment by Morph1984** [comment]
This issue has been reported to be fixed, closing.
