### ISSUE TITLE
Yuzu emulator freezing on Pokemon sword

### ISSUE THREAD

**Issue by Eroc444** [yuzu-emu/yuzu#4227]
Using Yuzu 300 

Game freezes to 0 frames and audio is still played.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4867447/yuzu_log.txt)

Happens after battles and during cutscenes.

OpenGl or Vulkan doesnt matter same issue.

**Comment by Jatoxo** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by Eroc444** [comment]
> This is an issue tracker for developers and not a support forum.
> Please use our Discord for support requests.

yea its an issue just saying it

**Comment by Jatoxo** [comment]
At least follow the guidelines for submitting an issue then. You didn't provide any version number, info on how to reproduce the issue, or attached a log file

**Comment by Eroc444** [comment]
> At least follow the guidelines for submitting an issue then. You didn't provide any version number, info on how to reproduce the issue, or attached a log file

fixed it

**Comment by FernandoS27** [comment]
Could you check in latest Mainline ?.

**Comment by Foebik** [comment]
Yuzu 311

This freezing has a chance to occur after a successful battle, just before exp is received.

**Comment by SSantxna** [comment]
> > Al menos, siga las pautas para enviar un problema en ese momento. No proporcionó ningún número de versión, información sobre cómo reproducir el problema ni adjuntó un archivo de registro
> 
> arreglado
how did you do it?  help please

**Comment by Apology11** [comment]
I am using Mainline Build 329:
To me it seems, that this problem has something to to with the framerate.
I noticed, that sometimes the framerate drops, right before receiving EXP and then the EXP bars go up faster than usual.
I turned VSync on an I have not encountered the freezing since.
Let me know if I can provide any further information.

**Comment by IdunnoManSeemsKindagAyTOme** [comment]
i have the same problem rn on y yuzu emulator

**Comment by german77** [comment]
This issue probably doesn't exist anymore. Re-open if needed with a new log

**Comment by Routled** [comment]
I'd like to reopen this issue since I've been getting the same problem and can't find a solution anywhere. I have checked posts on different forums reporting this issue as early as August 2020 without ever giving a solution.

Issue first encountered on earlier build that works for other games, I have done a new and updated fresh install of latest Yuzu build and Pokémon Shield (I suppose it's the same as Sword) but keep getting same results.

Issue first occured when starting on Route 3 from Motostoke city.

Outside of battle, freeze with sound when opening "key items" tab of bag:
[yuzu_log_1.txt](https://github.com/yuzu-emu/yuzu/files/7722919/yuzu_log_1.txt)

In battle, freeze with sound when selecting bag:
[yuzu_log_2.txt](https://github.com/yuzu-emu/yuzu/files/7722920/yuzu_log_2.txt)

Please let me know if there's been something done about this already, I'm kinda hoping for it so I can continue my journey.

**Comment by FernandoS27** [comment]
This is a "user exception" did you edit the save using pkhex or used a save from shield and/or newer game version?

**Comment by Routled** [comment]
I am terribly sorry, should have looked closer before requesting a reopen.
I was still running on PKM Shield 1.0.0, installed 1.3.2 and runs like a charm now.

Yuzu version 848
PKM Shield version 1.3.2
