### ISSUE TITLE
Zelda Breath of the Wild Crashes when entering new areas

### ISSUE THREAD

**Issue by jhol** [yuzu-emu/yuzu#4288]
When running Zelda: Breath of the Wild, Yuzu crashes when the player moves between areas:

```
dynarmic: POSIX SigHandler: Exception was not in registered code blocks (rip 0x0056482f7a359e)
[1]    4831 segmentation fault  ./_build/bin/yuzu
```

Git Commit: `mainline-636-2686-ge4c923d5c`

# Steps to reproduce
1. Load Breath of the Wild
2. Create a new game
3. Watch initial cut-scene
4. Yuzu crashes at the moment the player is about to be given control.

Yuzu also crashes when moving between areas in Hyrule in a pre-existing saved game.

# System
* Debian Testing
* nVidia GeForce GTX 1650
* Driver: 440.100

**Comment by Seryus** [comment]
I have the same issue when I follow steps 1 to 4.

The issue seems to occur during automatic save. I'm able to move once the control is given, before the save begins.

# Yuzu version
```
{
    "build_date": "2020-07-13T12:18:17Z",
    "build_fullname": "",
    "build_name": "Mainline",
    "build_version": "0",
    "scm_branch": "HEAD",
    "scm_desc": "mainline-636-2743-g6974e9f1b",
    "scm_rev": "6974e9f1b29eda84fca9d1da486431adad5d0900",
    "shader_cache_version": "10e0e6bb61e3703f11206673f30a0ecf"
}
```
# System
* Windows
* Intel(R) Core(TM) i7-10700K CPU
* nVdia GeForce RTX 270 SUPER
* Driver: 451.67

I truncated the log file to be able to upload it to Github, but nothing in it seems to be related to the issue. The part that I removed was lines that repeated from the launch of the game until the crash. I kept the last lines of the log file as is.
[yuzu_log_truncated.txt](https://github.com/yuzu-emu/yuzu/files/4917990/yuzu_log_truncated.txt)

**Comment by jhol** [comment]
Fixed in `mainline-0-321` - excellent work!
