### ISSUE TITLE
USB Device Pass through

### ISSUE THREAD

**Issue by jobisingh** [yuzu-emu/yuzu#4498]
I would like to request that USB device pass through for non-controller devices be added. Specifically for microphones and headsets. This may sound like a strange request to some, but it arrises from my desire to be able to play "Lets Sing 2019". It requires a microphone, either connected via usb, or wifi. I feel adding wifi capabilities would be a much more difficult solution.

**Comment by german77** [comment]
Microphone now works on yuzu. Since usb pass through is not simply feasible I consider this PR complete

**Comment by ocochard** [comment]
By microphone working on Yuzu, do you mean that specifying the correct USB microphone as "audio input" in global audio settings is enough to have USB microphone correctly detected in popular singing games ?

**Comment by Cynoic** [comment]
Not sure what mic input yuzu supports

**Comment by Funfelek** [comment]
@german77 can You explain ? 
'Microphone now works on yuzu' how and where to set it up ?

**Comment by german77** [comment]
On audio config select the microphone device.

**Comment by Puffin226** [comment]
@german77 i've tried playin' "Let's Sing ABBA&Queen" with the microphone from my "SteelSeries Arctis Nova Pro Wireless & SteelSeries Siberia V200" headsets and even though the mics were selected as "Input Device" in "yuzu Configuration -> Audio", no input was detected within the games, so yeah... not working

**Comment by EricScottLin** [comment]
this microphone input does not work on Let's sing 2024. And due to the lost of connection, it can not be posible to connect phone. So this game is not gonna be supported until usb device pass through.

**Comment by Quasi-Detective** [comment]
Can confirm that on yuzu 1723, microphone input does nothing in Let's Sing 2023 or Let's Sing 2024. It is not possible to start any song in either game because no input is detected, even though my microphone is on, working, and is selected as the Input Device in yuzu's configuration. Am I missing something, or is microphone input not _actually_ working? All I can find are people saying it doesn't work, so we either need better instructions or audio input needs to be fixed...
