### ISSUE TITLE
Paper Mario: Origami King - very slow performance even on good hardware

### ISSUE THREAD

**Issue by Joey11904** [yuzu-emu/yuzu#4581]
For some reason Paper Mario runs at 1 fps, after getting past the start screen and the initial cutscene with Luigi and Mario. 
[yuzu_log.txt.zip](https://github.com/yuzu-emu/yuzu/files/5125743/yuzu_log.txt.zip)
![Screenshot_2020-08-26_01-03-09](https://user-images.githubusercontent.com/33566635/91215636-fb665e00-e73e-11ea-816b-6ee33bd8154d.png)

**Comment by goldenx86** [comment]
This is not the appropriate channel to ask for support, this is for reporting issues.
Please ask either in the Discord server: https://discord.gg/u77vRWY
Or the forums: https://community.citra-emu.org/c/yuzu-support/14
Your issue is related to lack of a sufficient page file, I'll be glad to help you in the places i linked, so please contact me there.

**Comment by Joey11904** [comment]
@goldenx86 same thing happens on windows, and i do have a pagefile set up (on windows)

**Comment by Joey11904** [comment]
my bad, it turns out my pagefile wasnt big enough
it still runs pretty slow, but much better now (15 fps)
i'll close the issue now
