### ISSUE TITLE
shin megami tensei 3 nocturne graphic issue

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#4882]
<img width="1180" alt="20201101_135724" src="https://user-images.githubusercontent.com/66776795/97795521-95201f00-1c4a-11eb-8583-44af6149a6b3.png">

<img width="1178" alt="20201101_140730" src="https://user-images.githubusercontent.com/66776795/97795605-ba615d00-1c4b-11eb-9e2a-6407cba80484.png">

<img width="477" alt="20201101_140754" src="https://user-images.githubusercontent.com/66776795/97795610-bdf4e400-1c4b-11eb-8517-92b6042d21bf.png">

shin megami tensei nocturne 3 remaster have texture corrupt issue and some kind of shadow issue
hardware: i7 8700k 16gb ram rtx2080s
yuzu version: early access 1093
log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5470237/yuzu_log.txt)

**Comment by gidoly** [comment]
2nd and 3rd pictures are fixed on texture cache rewrite but 1st picture and weird flickering issue is still persist
https://youtu.be/zIJK55p1Auo

**Comment by Morph1984** [comment]
Fixed by #6597

**Comment by Metalcape** [comment]
This is still happening to me on the latest mainline build. As a workaround, setting GPU accuracy to extreme seems to fix the problem. This log is from the linux build but it also happens on windows. 
To cause the texure corruption I simply walked in and out of the first save point in the hospital, but it also happens on demi-fiend's body after going through some map transitions and in cutscenes.

![Screenshot from 2021-07-31 10-40-26](https://user-images.githubusercontent.com/11523873/127736654-b5afac29-1a42-4a30-bba3-98d609b056d6.png)
![Screenshot from 2021-07-31 10-41-01](https://user-images.githubusercontent.com/11523873/127736660-b09cb964-07d7-4e84-b89e-58c3171687b8.png)

CPU: i7-11800H
GPU: RTX 3060
RAM: 16 GB

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6911017/yuzu_log.txt)

**Comment by dysfunctionalriot** [comment]
This is also happening to me on mainline 708. Extreme GPU accuracy does fix the corrupted texture problem with no noticeable performance loss, but there are other glitches that happen on any GPU accuracy level. The protagonist's shadows flicker between defined shadow and a grey square on the floor. The screen also flashes with a corrupted texture randomly for about a frame. This is hard to capture due to the glitch being random, and lasting only a frame or two. I will try recording gameplay and uploading the exact frames with this glitch.

CPU: Ryzen 7 4700U
GPU: integrated graphics
RAM: 8GB

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6932750/yuzu_log.txt)

**Comment by benderscruffy** [comment]
is this still an issue ??
