### ISSUE TITLE
[Feature Request] Native DualSense support

### ISSUE THREAD

**Issue by ActualMandM** [yuzu-emu/yuzu#4958]
I would imagine this support would be similar to programs like RPCS3 and DS4Windows tapping into the DualShock 4/DualSense. Those programs can directly tap into the controller's rumble, lights, and gyro. Probably an additional thing that can be done is transferring HD Rumble data to the DualSense's haptic feedback.

**Comment by bunnei** [comment]
Probably still relevant, no need to close :)

**Comment by Hexality** [comment]
had this been implemented? I can't map my dualsense in the settings nor can use motions/rumble

**Comment by v1993** [comment]
Well, gyro part should probably be doable on Linux by now, if Sony got that driver into kernel already (contact me if you're interested). Rumble, lights and gyro, however, still have a way to go.

**Comment by Hexality** [comment]
Sadly I'm on Windows, but thx.

**Comment by german77** [comment]
Supported by #6244

**Comment by Zangetsu38** [comment]
@german77 rumble and haptik is not supported for now ?

**Comment by german77** [comment]
Rumble it's supposed to be supported. But it's not working on some controllers. Maybe it need a special setting enabled

**Comment by Zangetsu38** [comment]
> Rumble it's supposed to be supported. But it's not working on some controllers. Maybe it need a special setting enabled

No works for me, tested on usb/bt same

**Comment by Mutcholoko** [comment]
Okay, so after testing this for a bit, here are my findings:
The DualSense controller does not work with HD rumble. Actually, not even the joy-cons work with true HD rumble on Yuzu. That happens because either the HD rumble effect is divided into two parts and Yuzu is only playing 50% of it, or because the SDL rumble effects are not so precise. You can clearly check this by playing Mario Odyssey on Metro Kingdom with either the DualSense controller or the joy-cons (I haven't tried with the Pro Controller because I don't own one). If you ever played the game on an actual Switch, you'll remember exactly how the motorcycle HD rumble feels like: You can actually sense the motorcycle engine on your hands.
Using the joy cons or the DualSense only give you like 50% of that effect (it's a constant rumbling, without taking into account how fast the motorcycle is). If I could guess, I'd say the HD rumble is divided into two parts: The actual motorized "rumble", and a sound effect that is played through the voice coil. The rumble that Yuzu sends to the controller is actually only the motorized "rumble" part of the effect. You can tell this because if you connect a third party controller (without HD rumble) on the Nintendo Switch and play the same part of this game I mentioned, you'll see that the rumble feels the same. Lacking the other 50% of the effect kills the HD rumble completely.

I don't know if this commit was ever announced as "The DualSense now features HD rumble on Yuzu" or not, but I'm sure many people are getting it wrong from this issue here. [Take this post from PCGamingWiki as an example.](https://www.pcgamingwiki.com/wiki/Controller:DualSense#Games_with_adaptive_trigger_and_haptic_feedback_support) They state that 

> Emulator Yuzu allows emulating Nintendo Switch's haptic feedback known as HD Rumble on DualSense controllers.

And that doesn't seem to be the case, even on first party Nintendo controllers, from my testing.
Also, there's a strange bug in Mario Odyssey (it must be present in other games too, but I haven't noticed) where only half of the vibrations work. You can test this by pausing the game and scrolling down the options.

I'd love to see the DualSense actually being able to play HD rumble effects, that would totally be awesome. After searching the web, I truly couldn't find a definitive answer to "does the DualSense work with Yuzu's HD rumble?". It would be nice to hear directly from the devs of this amazing project. And I honestly don't think this issue should be closed, as it seems to still be relevant.

**Comment by RinMaru** [comment]
Yea HD rumble om Dualsense isnt complete and yes i can confirm SMO only ever plays a few of the rumble bits stuff like jumping is never felt

**Comment by gander-code** [comment]
my dualsense isnt even providing varying strengths of vibration, always 100%. I would expect some variation in strength, even if its not as precise as official HD rumble. This issue should maybe be open.

**Comment by africsnail** [comment]
Reopen?

**Comment by german77** [comment]
We have native support. Just not hd rumble.
