### ISSUE TITLE
SetProcessDpiAwareness Failure

### ISSUE THREAD

**Issue by RiverCityRansomware** [yuzu-emu/yuzu#51]
Yuzu - f53dc4c9

The current version of QT that Yuzu uses has a bug when trying to set dpi awareness causing incorrect scaling behavior on some monitors.

Example error:
```
SetProcessDpiAwareness(2) failed: COM error 0xffffffff80070005  (Unknown error 0x0ffffffff80070005), using 2
```

The fix is to update QT to 5.7.1 or later.

Pull Requests:
ext-windows-bin: https://github.com/yuzu-emu/ext-windows-bin/pull/1
Yuzu: https://github.com/yuzu-emu/yuzu/pull/66

**Comment by LDj3SNuD** [comment]
The DPI awareness is correctly set through the application manifest (`<dpiAware>true/PM</dpiAware>`).
Indeed, using an api monitor, the GetProcessDpiAwareness() api of Shcore.dll returns 0 (S_OK) with the out parameter set to 2 (PROCESS_PER_MONITOR_DPI_AWARE) from the QWindowsContext::processDpiAwareness() method of qwindows.dll.

The warning (qWarning()) is due the QWindowsContext::setProcessDpiAwareness() method of qwindows.dll that after calling the SetProcessDpiAwareness() api of Shcore.dll does not properly manage the returned value 5 (E_ACCESSDENIED).
Indeed the "SetProcessDpiAwareness function" page of MSDN states that: "E_ACCESSDENIED: The DPI awareness is already set, either by calling this API previously or through the application (.exe) manifest".
In addition, using a resource hacker to delete the application manifest the Qt warning disappears.

So it is just a Qt warning caused by a Qt bug that does not involve any problem for yuzu.

<br />

Updating yuzu to Qt 5.7.1 causes the Qt warning to disappear (unless the relevant Qt debug is enabled).

A post build solution could be to apply this patch (Qt 5.7.1 based) directly to qwindows.dll (platforms folder):
```
85C00F89F4000000
3C570F85F4000000
```

<br />

`Differences between versions 5.7.0 and 5.7.1 of qwindowscontext.cpp (qtbase)`
![png1](https://user-images.githubusercontent.com/35856442/35466897-9a341aa4-0308-11e8-8d4a-1ae24f1a3cbf.png)

`[Per monitor DPI aware | default condition]: yuzu displays correctly at 120 dpi regardless of the Qt warning`
![png2](https://user-images.githubusercontent.com/35856442/35466896-9a14e97c-0308-11e8-8a47-1e373e472149.png)

`[DPI unaware | forced condition]: yuzu displays wrongly at 120 dpi by deleting application manifest and patching qwindows.dll (FFD08BF885C00F89F4000000 -> 9090BFFFFFFFFF9090909090)`
![png3](https://user-images.githubusercontent.com/35856442/35466895-99f37508-0308-11e8-81c7-f351b29516ae.png)
