### ISSUE TITLE
Bug Report?/Feature request. Reducing the input delay

### ISSUE THREAD

**Issue by sweetenernj** [yuzu-emu/yuzu#5221]
A long issue that the Yuzu emulator has had for a while was input latency. The delay in which between you press a button and an action comes out on the screen. Before it was pretty bad compared to console but through numerous efforts of the devs it has been getting better and better. In this recent patch it was claimed to reduce input lag even further, and in my testing it does show that it is true; however unfortunately it is still slower then console. I'd say about half a frame to a full frame slower on Yuzu. Below are 2 of my tests one on Yuzu and the other on console. It involves me recording at 60FPS, using Zero Suit Samus (fastest attack in the game Frame 1), and after recording I count the frames individually after a button press. 

https://youtu.be/wbuuKMVnvyI (input delay test on console)
https://youtu.be/Xkr3L3XqTJQ   (input delay test on Yuzu)

*Specs: CPU: i7 8700K @5ghz
           RAM: 16GB 3200mhz @CL14 
           GPU:  Nvidia RTX 2080 FE
           SSD: Samsung 960 Evo
           Monitor: Alienware AW2521HF 240hz

**Disabled C-States, HPET, and other power saving functions that increase latency in the bios

***I use a Gamecube controller with the official GameCube adapter that is overclocked to 1000hz 

![image](https://user-images.githubusercontent.com/76490222/102915057-29d71a00-444f-11eb-8074-f96772d0192f.png)

****My Nvidia settings

![1](https://user-images.githubusercontent.com/76490222/102914896-eb415f80-444e-11eb-8a1a-d2772189ebba.png)
![2](https://user-images.githubusercontent.com/76490222/102914899-ec728c80-444e-11eb-85e5-16f468451105.png)

**Comment by german77** [comment]
A frame of delay is very good compared to the 4 - 14 fames that was reported a few months ago

**Comment by AndrewRosenthal** [comment]
If Yuzu is to become a true alternative to Nintendo Switch's unplayable online, the input delay will still need to be fixed. Ideally, we want to get to below console input lag to account for online. Can vouch that fixing this would get so many more eyes on the project.

**Comment by redpanda404** [comment]
Input latency with yuzu has been one of my biggest problems since I started using this emu. I'm hoping the devs can decrease the latency to make it less than the switch itself. They've cut a good amount of frames off, but just not enough.

Specs being
Ryzen 7 2700X
RTX 2070 Super
16gb RAM
480gb SSD
Monitor Acer XFA240 (144hz)
playing on an official GCC adapter 

even with the latest driver updates installed and all of my Nvidia optimizations. giving people more reasons to hop on yuzu will get more EA patrons too.

**Comment by sweetenernj** [comment]
> A frame of delay is very good compared to the 4 - 14 fames that was reported a few months ago

Yeah, I agree it is much better now. It does not mean it can't be better or the issue is completely gone. I think it will be completely ideal if it can at least match the Switch's delay or surpass it. Similar to how CEMU was faster then the Wii U. I know it is way easier said then done and there's a lot more that meets the eye that goes into it.

**Comment by sinBADNE** [comment]
100% agree. While my setup runs 1 frame off of the Switch's native 6 frames I know there are setups with 3+ frames extra. While it may not seem like much, it can make certain games frustrating. It would be amazing if we could get it reduced to the Switch's native 6 frames or lower it would really be helpful! I'm also running on the EA build with the official adapter. Hope this request gets through to the devs and they fix it!

**Comment by Barking-Frog** [comment]
Agreed that input latency is still an issue worth further investigation and improvement. With my current settings I've been seeing about 2 extra frames of latency compared to my switch console (8 frames vs 6).  Would love to see some further improvement to match the switch console experience through yuzu.

My 8 frames of input latency was found from testing in a way similar to sweeternj and my relevant specs include:
Ryzen 7 3700X
RTX 2070 Super
16gb RAM
1Tb SSD (don't remember exact spec)
Asus VG278QR (165Hz refresh rate, 0.5ms latency) 
official Wii U adapter
up to date graphics drivers and a relatively complete shader cache

**Comment by Trevor-Z** [comment]
Here on my system, using NSMBU as a reference, Yuzu has about 50% more input lag than Ryujinx (~90 ms x ~60ms).

Cemu still runs this game with the lowest input lag, by far (~40ms), and I'd love to understand why. But, to me, 60ms feels acceptable enough for 60fps action games, or at least way preferable than 90ms.

The main advantage with Ryujinx is that it allows you to uncap the framerate by setting vsync off, then you control these with the Nvidia Control Panel and RTSS. It really makes a difference in lowering the delay.

Maybe Yuzu could let us use that same trick?

**Comment by german77** [comment]
How you are measuring? Yuzu has from 1 to 2 frames of lag (1ms-30ms) of input lag. That's from windows detecting the input to the game showing the input. SSBU has a bad input system with 4-7 frames of lag

**Comment by Trevor-Z** [comment]
I make a video at 240fps with controller and screen both in the frame, then on NSMBU I press the jump button five times and count how many frames it takes from the button bottoming out until the first frame of Mario reacting. Then I average the values and multiply by the duration of one frame at 240fps, which is 4.2ms.

I know it's not the most precise method, and I know the results will vary from system to system, since there are other factors influencing the input lag, like the controller model, if it's wired or on bluetooth, and the monitor model. But it's a reasonably stable measurement, and works best to compare different emulators on the same system, since all of them run under the same conditions.

So, for instance, the last time I tested it I got these results, which are pretty much the same I've been getting for several months now:

Yuzu:
23
20
21
21
23
(Average: 21.6, x4.2ms = 90.72ms)

Ryujinx:
16
15
14
14
14
(Average: 14.6, x4.2ms = 61.32ms)

**Comment by german77** [comment]
Ryujinx started using the same input engine as yuzu. Input delay should be roughly the same since both emus now use the same drivers. If you are able to test again with both emus at the latest version it will be appreciated, any difference will result in polling method and emulation

**Comment by Trevor-Z** [comment]
Sure, here it is.

Yuzu 622, vsync off
21
23
20
23
22
Average: 21.8 frames at 240fps, x4.2 = **91.56 ms**

Ryujinx 1.0.6872, vsync off, using RTSS to cap the frame rate at 60fps
16
14
15
17
14
Average: 15.2 frames at 240fps, x4.2 = **63.84 ms**

Cemu 1.22.12c, vsync off
10
12
9
12
11
Average: 10.8 frames at 240fps, x4.2 = **45.36 ms**

**Comment by german77** [comment]
Thanks for the fast reply. I will try to see what's different.

**Comment by Trevor-Z** [comment]
I decided to do some more testing, this time changing my monitor's refresh rate from 75Hz (default) to 60Hz.

Yuzu:
60Hz                    146.37 ms
60Hz, RTSS on     127.57 ms
75Hz                      91.56 ms
Forgot to try 75Hz with RTSS on, but I did it once before and I think it was not much different, if at all.

Ryujinx:
60Hz                    131.77 ms
60Hz, RTSS on     132.30 ms
75Hz                    108.36 ms (Since vsync off on Ryujinx uncaps the frame rate, the game runs faster here)
75Hz, RTSS on       63.84 ms

Cemu:
60Hz                    49.70 ms
75Hz                    45.36 ms

There might be no real difference when values are close, like smaller than 5 ms. That could be an artifact from using too few samples to average frame time fluctuation.

Is this the amount of input lag people are generally getting with Yuzu and Ryujinx on 60Hz monitors? Also, it would be nice if someone else could do these same tests on a monitor with a higher refresh rate than mine.

**Comment by VentureNguyen** [comment]
Hi,

How can I find, add, or attach additional data from my setup, that may help with this feature request to reduce input lag? I am currently using shield tv controller via gamestream to my PC/yuzu. I understand there is additional delay with gamestream, but other emulators feel more responsive (almost unnoticeable).

Thanks!

**Comment by german77** [comment]
I'm working on something that should improve this issue. Please wait until I make a PR

**Comment by Trevor-Z** [comment]
A while ago I noticed the input lag had improved a lot, but today it was back to the usual amount.

I think the regression happened between EA versions 2040 and 2041:

Yuzu EA 2040 (vsync off, 75Hz refresh rate)
37.5ms
53.7ms
41.7ms
41.7ms
41.7ms

Yuzu EA 2041 (vsync off, 75Hz refresh rate)
95.4ms
83.3ms
95.8ms
87.5ms
95.8ms

BTW, I found an iOS app that helps with these measurements: https://isitsnappy.com/

**Comment by german77** [comment]
Interesting I have changed nothing recently are you on discord? I feel like you can test the WIP that will improve input in many areas

**Comment by Trevor-Z** [comment]
Sure, I'd love to. Just joined the server, I'm "Trevor_Z" there.

**Comment by german77** [comment]
I can't ping you there I'm "Narr the Reg"

**Comment by german77** [comment]
Thanks to trevor for testing. It was determined that yuzu doesn't have high input lag, it has a high delay on presented frames this PR #6787 reduces perceived input lag from 90ms to 40ms
