### ISSUE TITLE
Option to remove Amiibo [Feature Request]

### ISSUE THREAD

**Issue by Colmines92** [yuzu-emu/yuzu#5308]
I have a new feature request.
This is a necessary one and I suppose it's easy to implement too.

- Remove amiibo

TLoZ Links' Awakening DX reads the amiibo file, then asks you to remove it. As there is no such function you have no other choice than restart yuzu losing your progress..

**Comment by hadrianjones** [comment]
I can confirm it does the same issue for me. The game does detect the correct amiibo, but it also prompts the player to remove the amiibo before continuing and obtain the bonus dungeons chambers. Because there is no way to remove the amiibo at all -- and I have tried to load a dummy/empty bin amiibo file just to make sure whether it would work or not -- the game just cannot be completed 100%. A feature for the removal of amiibo reading will thus have to be implemented.

**Comment by 0rphon** [comment]
Same thing happens on SSBU. "There is data from another game written to this amiibo. To save super smash bros ultimate data select manage amiibo and delete its current data"

**Comment by hadrianjones** [comment]
**Update**

For players wanting to 100% Link's Awakening with the Amiibo feature, it is now possible through emulation with the Ryujinx one. They have very recently added Amiibo feature, and the game works perfectly with it. I tested it and problem solved.

I cannot confirm for any other game, but for Link's Awakening, it works with Ryujinx's own Amiibo feature. Thanks.

**Comment by Hexaae** [comment]
Ouch! Got the same issue today... TLoZ - LA stuck after amiibo detection:
![image](https://user-images.githubusercontent.com/8591462/143785701-4cd799e3-cb20-4b19-965c-4b9d60370050.png)
