### ISSUE TITLE
Something is not being freed after emulator stop

### ISSUE THREAD

**Issue by DarkLordZach** [yuzu-emu/yuzu#563]
Yuzu Version: 17f3590d 

![process](https://user-images.githubusercontent.com/5064800/41439534-26692dd6-6ff9-11e8-82aa-931956288b1d.PNG)

(Picture from VS debugger)

So this shows me loading Splatoon 2 waiting a bit then clicking Emulation>Stop in the menu.

The first jump is (what i assume to be) the allocation of ram for the game, but the little drop right before the bit I have highlighted is when i clicked stop. The highlighted part is after this with no game running.

I'm assuming that something wasn't deleted/freed properly or that functionality is not implemented. 

Not super high priority, noting this down because that seems like a bit leak.

Sidenote: Executing another game from this point seems to fix, but then clicking 'Stop' on that one does the same thing (different size of course)

**Comment by i30817** [comment]
I'd bet that the memory allocation array was resized and never dropped on the (correct) expectation that it's going to be reused next time a game is loaded...

This is something that 'isn't even wrong'. Only if you can see it growing without limit after loading several games in a row do you have memory leak. 

There is a case to expect memory to be returned to the system, but it's not a very good one imo. Especially because that causes 'false expectations' like 'memory will be returned when i 'pause' the emulation to watch youtube (something which will never be true).

**Comment by DarkLordZach** [comment]
Insightful.

In that case, after loading one game, stopping, and then loading another it uses about as much ram as intended so no leak there.

Sorry for bothering.
