### ISSUE TITLE
Game in Yuzu not launching on any secondary Monitor

### ISSUE THREAD

**Issue by Quadrubo** [yuzu-emu/yuzu#5986]
I'm using Yuzu Early Access Version 1480. 

When I'm starting Yuzu on my main Monitor and move it to my second monitor (or when I'm starting Yuzu from my second monitor directly) if any game is being launched, it will be stuck on the launching screen.
I have a triple Monitor Setup, (Monitor1: 2560 x 1440 @144hz 125% Scale, Monitor2: 3840x2160 @60hz 200% Scale, Monitor3: 1920x1080 @60hz 100% Scale).

log file: 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6027280/yuzu_log.txt)

Screen Recording:
https://youtu.be/6wdsUguIcUM

Sorry if this is wrong btw, this is my first issue, on discord I was being told to submit it here :)

**Comment by CAlbertSM** [comment]
I have a dual setup, I updated my main monitor today before opening Yuzu and got stuck on forever loading, closed yuzu and moved it to my new main and game loaded, then changed the main monitor back to my old one, and game got stuck on loading, moved yuzu back to the old main and game loaded, so I can confirm this issue is happening.

**Comment by vschembari** [comment]
This is an issue i am still experiencing on build 810 btw

**Comment by gidoly** [comment]
issue seems fixed here feel free to reopen if it is still persist

**Comment by DarkLouie** [comment]
The issue seems to still persist on my PC have to reset all setting to get it to work again.
