### ISSUE TITLE
zipcmp not listed under deps on building/linux

### ISSUE THREAD

**Issue by maxsupermanhd** [yuzu-emu/yuzu#6031]
When configuring without package `zipcmp` installed on Ubuntu 20.04 cmake fails with following message:
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-targets.cmake:93 (message):
  The imported target "libzip::zipcmp" references the file

     "/usr/bin/zipcmp"

  but this file does not exist.  Possible reasons include:
  ```
  UPD: also same story for `zipmerge` and `ziptool`

**Comment by lat9nq** [comment]
It's not listed because it's not required. Make sure you are following [this guide](https://github.com/yuzu-emu/yuzu/wiki/Building-for-Linux), your packages are updated and you are using Ubuntu's packages for Focal, and that you are building from the [yuzu source](https://github.com/yuzu-emu/yuzu-mainline).

I was unable to reproduce this issue on my Ubuntu 20.04 VM. (yuzu builds fine, zipcmp and friends are not installed.)

**Comment by kwyxz** [comment]
It is listed as required by the exact guide you link as a dependency for Debian / Ubuntu, and strictly following the instructions on Debian Sid I run into exactly the same issue.

```
❯ cmake .. -GNinja -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10     ─╯
...
-- Target architecture: x86_64
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-targets.cmake:93 (message):
  The imported target "libzip::zipcmp" references the file

     "/usr/bin/zipcmp"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "/usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-targets.cmake"
  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-config.cmake:42 (include)
  externals/CMakeLists.txt:67 (find_package)

-- Configuring incomplete, errors occurred!
See also "/usr/local/src/yuzu/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/yuzu/build/CMakeFiles/CMakeError.log".
```
The solution is to remove libzip-dev then run cmake again.

**Comment by lat9nq** [comment]
> It is listed as required by the exact guide you link as a dependency for Debian / Ubuntu

The string `zipcmp` does not match anything on that web page.

The issue is a regression in the `libzip-dev` package, and I was able to reproduce it on my Bullseye VM (20.04 still seems unaffected.) This is a "not our problem" type of issue and needs to be brought up with the maintainers of the package.
