### ISSUE TITLE
Be able to exit emulator when using fullscreen (hotkeys don't work)

### ISSUE THREAD

**Issue by elcosomalo1** [yuzu-emu/yuzu#6043]
So that's it, a major feature is missing: be able tu use the hotkeys to control UI of the emu while in fullscreen; you cannot exit the emulation when playing in fullscreen if you first don't press ESC to go to window mode. This is annoying and is a basic feature for people like me using the emu with for example, Steam.

**Comment by Svarr** [comment]
The only emulation related hotkey working in fullscreen for me is F6 (Restart), which crashes yuzu.
Back to windowed, F6 doesn't work but F5 (Stop) does.

**Comment by KiNGKiMO** [comment]
Now with overlay applets I think it would be great if they're used in fullscreen mode for "Exit yuzu".

**Comment by Svarr** [comment]
Exactly, some kind of ingame menu that is operable by the controller would be great!

**Comment by oblitum** [comment]
RetroArch, which now integrates very well with Steam BigPicture, offers for a long time an option to have a joystick key combination to exit it. I generally set it to select+start. I wish something like that was available in yuzu, so that I could avoid reaching keyboard/mouse to be able to close it.

**Comment by heinermann** [comment]
Working on this

**Comment by elcosomalo1** [comment]
wow... guys... I have a real switch now so... yeah... you took your time... 
I'm not interested in Yuzu anymore but other people are for sure. 

The next time, try to think this better please... some core functionalities should be there before other "features". 
Expecting players to leave the couch to exit the emu was a bad idea IMO.

Good luck!

**Comment by oblitum** [comment]
I learned to better integrate (_any_) emulator with Steam, this is what I use:

![](https://0x0.st/-EaE.png)

This chording configuration works wonders for me for multiple kinds of emulators/applications. I've set directional pads to keyboard arrow keys, and some base buttons to usual shortcuts for leaving applications. For Dolphin I just need to press the <kbd>guide-button + circle</kbd> to exit it, because Dolphin exits with <kbd>Esc</kbd> alone for me. For Cemu, I have to press <kbd>guide-button + circle</kbd> to generate an <kbd>Esc</kbd> for it to exit fullscreen, it won't close right away though, like Dolphin does, so I use <kbd>guide-button + triangle</kbd> to generate an <kbd>Alt + F</kbd> to bring up the file menu, then I simply click <kbd>guide-button + X</kbd> for <kbd>Enter</kbd> key, since exit is the sole option in the menu. For yuzu, I have to press <kbd>guide-button + circle</kbd> to exit fullscreen (yuzu really requires this otherwise any other keyboard input is ignored, as well as steam overlay), then <kbd>guide-button + triangle</kbd> to bring the file menu, then <kbd>guide-button + down</kbd> for selecting the last option, then <kbd>guide-button + X</kbd> for <kbd>Enter</kbd> to exit it.

On ArchLinux at least, this all works fine.

**Comment by heinermann** [comment]
> wow... guys... I have a real switch now so... yeah... you took your time... I'm not interested in Yuzu anymore but other people are for sure.
> 
> The next time, try to think this better please... some core functionalities should be there before other "features". Expecting players to leave the couch to exit the emu was a bad idea IMO.
> 
> Good luck!

I'll do what I want. (ノಠ益ಠ)ノ彡┻━┻

**Comment by german77** [comment]
Do you care to share more details. I'm going to add controller hotkeys soon

**Comment by heinermann** [comment]
> Do you care to share more details. I'm going to add controller hotkeys soon

I'm trimming down main.cpp by removing a lot of duplicate code, mainly for the biggest offenders like `InitializeHotkeys`. Not having the duplication meant that nothing worked in fullscreen, so I added the actions in `ConnectMenuEvents` to the window itself (via addAction) so that hiding the menu wouldn't also disable the actions. It bothered me while adding the TAS menu so I'm just following up on it.
