### ISSUE TITLE
Re-compile yuzu linux version for macOS

### ISSUE THREAD

**Issue by KohlerVG** [yuzu-emu/yuzu#6049]
Hello,

I have a question about re-compiling the yuzu Linux version to work on macOS, sense Linux is similar to the macOS kernel, is there a way to make this work using a 3rd party program out there like [Macports](https://www.macports.org/)?

Thanks,
Kohler

**Comment by EliEron** [comment]
Short answer: No, it's not possible, at least not in the way you are thinking.

Long answer: Compiling Yuzu for macOS is not really the main issue for compatibility, that can already be done with some minor patching to the source code. The issue is that macOS does not support OpenGL 4.6 or Vulkan which are the graphics APIs required by Yuzu to properly render games. macOS only supports a graphics API called Metal. And while there are projects attempting to translate Vulkan API calls to Metal they are still pretty immature and not at a stage where they work well with Yuzu.

So ultimately yes, you can compile Yuzu for macOS with some work, but you won't be able to run pretty much anything that uses a 3D engine, which includes most commercial games, even ones that have a 2D appearance. If you are still interested look at this PR #4165 that is where people are currently adding patches to make Yuzu compile to macOS. But again you won't be running practically any games using that PR.

**Comment by vesper8** [comment]
Crossover 20 ships DXVK and MoltenVK and it works surprisingly well.

Here's it running RE3: https://www.youtube.com/watch?v=Cic_IWjAo2E&t=154s

Dark Souls Remastered: https://www.youtube.com/watch?v=HcBq9x3yzHI&t=245s

Sekiro: https://www.youtube.com/watch?v=BuXDO-SS7ZQ&t=684s

Metro Exodus: https://www.youtube.com/watch?v=GUG8SbrFj-A&t=305s

So while it still has a long way to go.. it is already pretty impressive. It would be nice to have MacOS builds available again so we can test games and see just how badly / not-so-badly they are rendering
