### ISSUE TITLE
Port to UWP, Xbox Series X|S and Xbox One

### ISSUE THREAD

**Issue by adamcarter1** [yuzu-emu/yuzu#6059]
Would love a UWP port to run on xbox series S/X in dev mode

**Comment by CrusadingNinja** [comment]
There are many factors that make this impossible at the moment. First of all, this isn't possible without a DirectX backend on Yuzu as Xbox only has support for that API. In addition, dev mode actually has quite a lot of restrictions including a hard 5 GB limit of the unified memory on the Xbox that can be utilized, and yuzu consistently uses more than 5 GB.

**Comment by Morph1984** [comment]
Closing due to the reasons above and #5827

**Comment by juanleo320** [comment]
The question here shouldn't be if you guys will make a port, anybody with the source code can do it. The question is if you guys will have dx12 support so that if you or anybody were to make a port or could work. I know you pretty much would have to to rewrite everything but think of the possibilities of your emulator pretty much working on every new next gen system, you guys could even charge for it. Also about the size limitations that can be changed on the configuration that is why PS2 games work and wii games also do.

**Comment by RenanZX** [comment]
I would be very happy to support a Patreon for the project if anyone ports it to Xbox Series consoles, and I'm sure that many people are interested in running Switch games on Xbox.

**Comment by Soheilsadri278** [comment]
> I would be very happy to support a Patreon for the project if anyone ports it to Xbox Series consoles, and I'm sure that many people are interested in running Switch games on Xbox.


what happens for project ?
