### ISSUE TITLE
Zelda: BotW crash in loading screen using Vulkan.

### ISSUE THREAD

**Issue by buggy33** [yuzu-emu/yuzu#6179]
Yuzu: **yuzu Early Access 1580**
Hardware: **Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz; AMD Radeon RX 460 Graphics**
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6291384/yuzu_log.txt)

Steps to reproduce:
1. Start Zelda: BotW
2. Choose 'New Game'.

RESULT:
Game crash in loading screen. It happens only using Vulkan. OpenGL works but performance sucks.

**Comment by steven-a-wilson** [comment]
I'm also running an AMD GPU (RX 5700 XT) on Arch Linux and get a crash like this, but only when using AMDVLK. If I use RADV, I don't get the crash (although there are other issues documented elsewhere). There's an issue in Arch Linux that if the `amdvlk` package is installed, RADV can't be used by default, although it's possible to override this with environment variables [1].

[1] [FS#69289 - [amdvlk] Installing overrides all Vulkan apps to use AMDVLK by default instead of RADV](https://bugs.archlinux.org/task/69289)

**Comment by hcyang99** [comment]
Yuzu: yuzu 663
Hardware: Intel i7-8809G; AMD Radeon RX Vega M GH Graphics (Driver Version 21.5.2)
OS Version: Windows 10 21H1 (19043.1052)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6683628/yuzu_log.txt)

Step to reproduce:
1. Start Zelda: BotW

Result:
Game crashes at "Nintendo Presents". Happening only with Vulkan. OpenGL works but extremely slow.

**Comment by ameerj** [comment]
Is this crash still reproducible on the latest yuzu?

**Comment by mistermodcreator** [comment]
> Is this crash still reproducible on the latest yuzu?

Yes, it is! Getting the same crash, maybe it happens when the game world is loading? When starting a new game, it crashes when the screen turns white and when loading a game it crashes at ~80%.

Yuzu: 1009
Hardware: AMD Ryzen 5 2600 @4 GHz; AMD Radeon RX 580 8GB Saphire Nitro+
Driver Version GPU: 21.50.21.01-220331a-378260E-AMD-Software-Adrenalin-Edition
OS Version: Windows 10 21H2 (19044.1645)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8646060/yuzu_log.txt) (Loading savegame)

**Comment by mistermodcreator** [comment]
An Update for everyone having the same problem:
I got it fixed. I'm not shure what fixed it, but I'll tell you what I did.

1. I uninstalled yuzu and deleted everything yuzu-related in AppData/Roaming and AppData/Local, because I was disappointed.
2. I installed MESA 22.1.0 mingw driver from [here](https://github.com/pal1000/mesa-dist-win/releases) system-wide, followed by a restart.
3. I followed [this guide](https://github.com/PrincessAkira/road-to-yuzu-without-switch#setup) to setup yuzu again and loaded Breath of the Wild. Worked now.

Also, Yuzu was updated a few times during me being disappointed and me installing MESA driver.

**Comment by G-Spawn** [comment]
Glad you managed to fix it. Please feel free to reopen should this issue happens again 🙏

**Comment by Delikt** [comment]
Still crashing on Steam Deck in Menu and also Ingame (not always but its a matter of Time)

**Comment by G-Spawn** [comment]
If you dont mind please make new issue when you can yeah :p @Delikt . Devs are aware of some recent issues for some users with botw.
