### ISSUE TITLE
Prevent screensaver while in-game (Xorg)

### ISSUE THREAD

**Issue by Mynacol** [yuzu-emu/yuzu#6262]
I enjoy playing Switch games on my computer a lot. Thanks for this very fast and pleasant experience.

One big annoyance I encountered is the screensaver kicking in during gameplay. To work-around this, I set `xset s off -dpms` before gameplay. As this is manual and does not revert back after ending gaming, I propose to disable the screensaver while in-game. Video players like mpv or vlc do the same if you want to know how this is done.

The alternative would probably be to educate my machine to not activate the screen saver if there is joystick/controller input.

What's your stance on screensavers?

Technical Details:
* Arch Linux
* Xorg / X11
* yuzu-20210426-758433fe2.AppImage
* gaming with Dualshock 4 controller (no mouse/keyboard input during gameplay)

**Comment by steven-a-wilson** [comment]
This also bothered me recently, and I'm a software developer with some (embedded) Linux and Qt experience. So I should clearly fix it myself, right?

That being said, I just spent a couple hours thinking that this should be easy and essentially coming up empty. I figured that the freedesktop.org crowd would have definitively solved this a decade ago [1], but as far as I can tell it's still a garbage fire in practice. For any given application that inhibits screensaver/sleep "successfully", there appears to be a distinct mix of unreliable methods gated by a distinct mix of questionable platform/DE/window system tests. I'd love to be proven wrong on this, but as far as I can tell there is still no serious solution to this problem for Linux generally. Everyone seems to be throwing their own custom concoction at the wall and hoping that something will stick.

[1] The xdg-screensaver script allegedly solves this problem, but upon further examination its requirements seem to be incompatible with the limitations of QWidget::WinId() [2] [3]).

[2] "WindowID must be the X Window ID of an existing window of the calling application. The window must remain in existence for the duration of the suspension." [what about Wayland systems?]

[3] "This value may change at run-time. An event with type QEvent::WinIdChange will be sent to the widget following a change in window system identifier."

**Comment by bibitocarlos** [comment]
You can use lightson : [https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwif8tH1ksLwAhWhdN8KHe3dBTgQrAIoA3oECAMQBA&url=https%3A%2F%2Fbbs.archlinux.org%2Fviewtopic.php%3Fid%3D145324&usg=AOvVaw0jaI0vmjuDfq2IgGepEa7u](url)

**Comment by v1993** [comment]
SDL provides functions for inhibiting screensaver, yuzu probably can use those.

**Comment by steven-a-wilson** [comment]
I tried a solution based on running xdg-screensaver, but it didn't work in my environment (Arch Linux with KDE Plasma 5.21.5). Apparently, the trick is to send a particular D-Bus message on the session bus _and stay connected to the session bus_. xdg-screensaver doesn't do the latter part because it uses the dbus-send program to send messages [1].

SDL has code for this (and in fact yuzu-cmd seems to already do it as a side effect of creating an SDL window), but it's tied to the window subsystem and uses SDL's internal framework for dynamic linking (to avoid creating a hard runtime dependency on libdbus), so I don't think it's straightforward to use it as-is in the Qt frontend. However, the general approach could be adapted.

[1] https://bugs.kde.org/show_bug.cgi?id=381160#c4

**Comment by steven-a-wilson** [comment]
After looking at it some more, I still think this is a bit messy but ultimately tractable. The main question I have at this point is which approach to dealing with the D-Bus interfaces would annoy maintainers the least:

- Use QtDBus (specific to Qt, creates a dependency on libQt5DBus and libdbus)
- Use QLibrary to load libdbus functions (specific to Qt, but only requires libdbus and can fail gracefully without it)
- Use dlopen()/dlsym() to load libdbus functions
- (Something else?)

**Comment by steven-a-wilson** [comment]
I'm still sporadically working on this. I have a rough draft of an implementation that uses the D-Bus org.freedesktop.ScreenSaver "Inhibit" and "UnInhibit" methods by loading the relevant libdbus functions via DynamicLibrary. This works as expected on Arch Linux with KDE Plasma 5 (both X11 and Wayland) and on Fedora 34 with Gnome 40 (only tried on X11 because that machine is using Nvidia drivers). A fair bit of general cleanup is still needed, and the error handling/logging isn't great at this point, but it at least seems to me that it has the right general shape to be a reasonable solution. This is all wrapped in a single SleepPreventer class with PreventOSSleep and AllowOSSleep methods. The dream is that it "just works" without requiring the caller to jump through any platform/framework/toolkit-specific hoops such as passing an X11 window ID or calling a method from the event loop.

My current plan for supporting less common configurations is to fall back to periodically running "xdg-desktop reset" in a separate thread if the Inhibit method fails or libdbus is absent altogether. This handles a polling model as opposed to a lock model; suffice it to say that this is apparently a point of disagreement in the field of screensaver inhibition and there are environments that only support one or the other. That script is somewhat buggy, but it looks like the most substantial bugs relate to environments that support the Inhibit method. 

Does anyone have an opinion on whether it's especially preferable to use DynamicLibrary rather than dlopen()/dlsym()? I'm leaning toward the position that DynamicLibrary doesn't really pull its weight for a Unix-specific code path, and using dlopen()/dlsym() would make it more portable to other projects that might be interested in using it. I'd also like to release this code under a permissive license for that reason (although I have no objection to signing a CLA that allows yuzu to distribute it under an entirely different license). 

@Mynacol What screensaver/configuration are you using? Is it configured through a DE, a separate package like XScreenSaver running via .xinit/.xprofile/.xsession, "raw" DPMS (e.g. configured via xorg.conf or xset), or what? I hope that my intended implementation will work with any of those, but I'd prefer to actually test in a similar environment before claiming that I've addressed an issue that you opened.

**Comment by Mynacol** [comment]
Thanks for looking into this. Even better if it works under Wayland as well.

I am running i3 on Xorg (thanks Nvidia!) without a special screensaver program. Xorg itself manages screen blanking/DPMS and I can control it with xset.
Hook me up with an AppImage if I should test on my setup.

**Comment by steven-a-wilson** [comment]
I finally got this cleaned up to the point where I don't feel like it's missing anything major, and I've published a "release" AppImage for anyone who's interested in testing:

https://github.com/steven-a-wilson/yuzu-mainline/releases/tag/idle-inhibitor-test0

**Comment by v1993** [comment]
@steven-a-wilson yuzu-mainline should not be used for forks, use this very repository instead. When you feel like you're done, send PR and we'll sort it out.

As for testing, that's what Early Access builds are for, no need to start your own initiative in place which will gather very few testers anyways/

**Comment by rscm** [comment]
I bypass this enabling coffee mode, hope this gets fixed soon

Thanks for your work!

```
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.1.6
Codename:	Pahvo
```
DE: Budgie
