### ISSUE TITLE
Cmake can not found qt5 in building for macOS

### ISSUE THREAD

**Issue by jiachenning** [yuzu-emu/yuzu#63]
I followed the guide of [Building-for-macOS](https://github.com/yuzu-emu/yuzu/wiki/Building-for-macOS), after run `cmake .. -DCMAKE_BUILD_TYPE=Release`, I got a error.

    -- Target architecture: x86_64
    <FindSDL2.cmake>
    </FindSDL2.cmake>
    CMake Error at CMakeLists.txt:285 (find_package):
    By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "Qt5", but
    CMake did not find one.

    Could not find a package configuration file provided by "Qt5" with any of
    the following names:

      Qt5Config.cmake
      qt5-config.cmake

    Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
    to a directory containing one of the above files.  If "Qt5" provides a
    separate development package or SDK, be sure it has been installed.

    -- Configuring incomplete, errors occurred!
    See also "/Users/ninja/tool/yuzu/build/CMakeFiles/CMakeOutput.log".

Seems `export Qt5_DIR=$(brew --prefix)/opt/qt5` not work.

After google I use the ` export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.8.0_1 ` instead, now it works.

Maybe the wiki of [Building-for-macOS](https://github.com/yuzu-emu/yuzu/wiki/Building-for-macOS) should be update?

Environment:

- macOS 10.13.1
- cmake 3.10.1
- qt 5.8.0.1

**Comment by MerryMage** [comment]
FYI, macbrew symlinks `/usr/local/opt/qt5` to the latest version of qt5 you have installed. Today (17th Jan 2018), that would be 5.10.0_1, which would be located at `/usr/local/Cellar/qt/5.10.0_1`.

I will not update the wiki instructions because: (a) they are correct, and (b) they would become out of date if we hardcode a version number.

**Comment by bunnei** [comment]
Please ask on Discord for support on building yuzu, the issues tracker is for emulator bugs and tasks.

**Comment by Joebeazelman** [comment]
Let me save everyone an evening in hell. If you already have qt5 installed, but not qt@5, then uninstall it and follow the directions below:

% brew install qt@5
% export CMAKE_PREFIX_PATH=$(brew --prefix)/opt/qt@5/lib/cmake/Qt5

Test to ensure cmake finds the necessary make files. If you want to make it permanent, do the following:

% echo  'export CMAKE_PREFIX_PATH=$(brew --prefix)/opt/qt@5/lib/cmake/Qt5' >> ~/.zshrc

RANT:  The reason software sucks so bad is that the simplest configuration turns into hours thanks to an operating system invented in 1969. It was supposed to be sent back to the bowels of hell decades ago. But a generation of insecure macho nerds who eschew usability in order to impress others.
