### ISSUE TITLE
we need a mii maker

### ISSUE THREAD

**Issue by Ritzbitz3** [yuzu-emu/yuzu#6351]
its just a thing that i think many people would want cuz miitopia is a great game and another game that has miis will benefit i feel like this is something we need

**Comment by BSoDGamingYT** [comment]
Please follow the issue format. stating game and function reported/required. Paired with a game log

**Comment by v1993** [comment]
@BSoDGamingYT I don't really think it's reasonable to follow an issue format for what is a feature request.

Does it belong on issue tracker is another question tho. Since GitHub allows multiple issue templates, perhaps create one for feature requests? Or, if they don't fit here, you can link users to discord there, reducing amount of unfitting reports.

**Comment by german77** [comment]
Closing in favour of #6429
