### ISSUE TITLE
NINJA GAIDEN Sigma stop working after cutscenes videos

### ISSUE THREAD

**Issue by kiaoru** [yuzu-emu/yuzu#6474]
after video done, fps drops to 0 forever

**Comment by gidoly** [comment]
Post log for provide more detailed  information about issue

**Comment by kiaoru** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6661936/yuzu_log.txt)

**Comment by kiaoru** [comment]
> Post log for provide more detailed information about issue

here

**Comment by G-Spawn** [comment]
The emulator will require changes in order to fully boot the cutscenes without issue. A temporary remedy is to just hit the A button before letting it finish to skip it and the game works fully. This workaround applies to all of the 3 games since they all utilize the same intro cutscene to boot and output same error when not skipped and it softlocks.

**Comment by kiaoru** [comment]
ooo its softlocks. yes i press A button and will go to main menu, game runs nice, but in chapter 2 has cutscene too that cannot be skipped

**Comment by G-Spawn** [comment]
Hopefully it'll be fixed in future! Thank you for posting the log it should help them address it whenever they get the chance.

**Comment by kiaoru** [comment]
ok, thanks for answer my problem, I will wait for the fix :)

**Comment by german77** [comment]
Fixed by #6504
