### ISSUE TITLE
After version 665 Ultimate Mod Manager is not longer able to properly access data.arc files needed to implement mods.

### ISSUE THREAD

**Issue by TeamJustMark** [yuzu-emu/yuzu#6554]

**Comment by lat9nq** [comment]
This is caused by #6472 because now we report an actual atmosphere version. This cauess UMM to look in `sdmc/atmosphere/contents/01006A800016E000` instead of `sdmc/atmosphere/titles/01006A800016E000` on Linux, or `sdmc/yuzu/load/01006A800016E000/UMM` on Windows. 

Please move the data.arc to `sdmc/atmosphere/contents/01006A800016E000` and try again.

**Comment by TeamJustMark** [comment]
Unfortunately after moving the data.arc to
yuzu/sdmc/atmosphere/contents/<games> it still had the same error appear
stating that data.arc could not be found.

**Comment by lat9nq** [comment]
The data.arc is in the romfs directory? I was thinking from memory and forgot that it needed to be there.
So the full path should be `sdmc/atmosphere/contents/01006A800016E000/romfs/data.arc`

**Comment by TeamJustMark** [comment]
You're a godsend. Thank you so much.

**Comment by lat9nq** [comment]
No problem, just FYI you can also now right click the game -> Dump RomFS -> Dump RomFS to SDMC and it'll put the data.arc in the atmosphere/contents directory, so when the game updates you don't need to copy/move the data.arc from the dump directory to use it with UMM.

This issue can be closed.
