### ISSUE TITLE
[Luigis Mansion 3] [Vulkan] Crash at cinematic

### ISSUE THREAD

**Issue by PacoAvelar** [yuzu-emu/yuzu#6624]
Game : Luigis Mansion 3
CPU : i7 1165G7
GPU : Intel Iris Xe - Driver Version : 9670
Ram : 16GB
OS : win 11
Yuzu EA : 1869

Config: Default

Issue :
Game Crash at cinematic

![image](https://user-images.githubusercontent.com/29181120/125253634-3de54a80-e2bf-11eb-9f70-bb0d505fcd89.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6799779/yuzu_log.txt)

**Comment by codbugpatrol** [comment]
I can confirm that this is happening in Nvidia as well (latest drive 471.11 but old card, GTX 670)

Host CPU: AMD Ryzen 5 3600 6-Core Processor | AVX2 | FMA
Host OS: Windows 10 (10.0)
Host RAM: 15.93 GB
Host Swap: 19.53 GB
Driver: NVIDIA 471.11.0.0
Device: NVIDIA GeForce GTX 670
Vulkan: 1.2.168

@PacoAvelar, may you please remove the [Iris Xe] tag in the title to make this more generic ?

To reach this screen, I've removed updates and dlscs, otherwise it didn't pass the "Launching" screen.

**Comment by luigiplus** [comment]
I confirm that this is happening too in vulkan AMD r9 380 latest driver.
there are some areas ingame where  always crash:
-near the car before picking up the vacuum cleaner

cpu i5 3570  8gb ram windows 10 last update.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6803465/yuzu_log.txt)

**Comment by PacoAvelar** [comment]
> I can confirm that this is happening in Nvidia as well (latest drive 471.11 but old card, GTX 670)
> 
> Host CPU: AMD Ryzen 5 3600 6-Core Processor | AVX2 | FMA
> Host OS: Windows 10 (10.0)
> Host RAM: 15.93 GB
> Host Swap: 19.53 GB
> Driver: NVIDIA 471.11.0.0
> Device: NVIDIA GeForce GTX 670
> Vulkan: 1.2.168
> 
> @PacoAvelar, may you please remove the [Iris Xe] tag in the title to make this more generic ?
> 
> To reach this screen, I've removed updates and dlscs, otherwise it didn't pass the "Launching" screen.


@codbugpatrol Are you using "Disable Dynamic Res" mod ?

**Comment by codbugpatrol** [comment]
@PacoAvelar no, the "Disable Dynamic Res" mod is disabled.
I've made some attempts  to pass the cinematic. Usually it freezes exactly where you've took the screenshot, other times, it pass a little bit of that. The problem seems to be related to memory, since it is sky rocketing during the cinematic, almost reboot the entire desktop.

**Comment by PacoAvelar** [comment]
@codbugpatrol please try using the mod, that is recommended to run this game

**Comment by codbugpatrol** [comment]
@PacoAvelar , with the Disable Dynamic Res on is working. With Intel Iris Xe is not working at all ?

**Comment by PacoAvelar** [comment]
@codbugpatrol not working at all

**Comment by PacoAvelar** [comment]
Issue solved on latest intel driver 9684
