### ISSUE TITLE
DELETE ME

### ISSUE THREAD

**Issue by IanHollow** [yuzu-emu/yuzu#6681]

**Comment by PacoAvelar** [comment]
Can you post the driver version?
 Task manager, gpu. Should hace the driver version

**Comment by IanHollow** [comment]
sorry just edited it

**Comment by RinMaru** [comment]
yea vulkan has issues at least its not this bad. I guess ill post this here since its generally VK issues

Windows 10
AMD RX 480 4GB Adrenalin 21.7.1
20GB DDR4 RAM
Ryzen 5 5600 6Cores 12 Threads

![Screenshot 2021-07-19 094331](https://user-images.githubusercontent.com/15071652/126169591-4f270de5-40ad-4ecb-84fc-b8d56631ccc0.png)

**Comment by cam1170** [comment]
I don't know if this is the same issue, but I currently still have the weird eyes, as well as a display corruption of pink squares, even after quitting yuzu, the first time leaving Link's room. It goes away (mostly) when I turn my monitor off and on.
Windows 11
AMD RX 6600 XT 8 GB Adrenalin 23.4.3
16 GB DDR4 RAM
Ryzen 5600 6 Cores 12 Threads
Yuzu 1430
