### ISSUE TITLE
Error loading amiibo in Metroid Dread

### ISSUE THREAD

**Issue by Hootek** [yuzu-emu/yuzu#7143]
Hi, I'm having an error loading amiibo files in Metroid Dread. A message appears that amiibo is not supported, but it is to work.

**Comment by german77** [comment]
Amiibos are copyrighted material. Please don't share them

**Comment by MrPete1985** [comment]
Get this error when loading Dread E.M.M.I. or Samus Amiibo.  I know my dumps are good because I was able to program to RFID tags and use them on a real unmodified Swit
![2021-10-11 21_19_48-yuzu 776 _ Metroid Dread (64-bit) _ NVIDIA](https://user-images.githubusercontent.com/41525872/136875025-0b67a68a-461b-483f-8298-c11ab9337a66.png)
ch
