### ISSUE TITLE
yuzu segfaults with vulkan backend on Intel anv linux

### ISSUE THREAD

**Issue by davidbepo** [yuzu-emu/yuzu#7709]
this happens on both early access and latest git versions and i dont know when it began to happen but im certain it worked at some point
the log on console is Unhandled SIGSEGV at rip 0x00556f616d6f59
it works fine on AMD RADV, both systems have Mesa 21.3.4
the crash happens even before the loading screen appears
let me know any more info that could help

**Comment by pacoa-kdbg** [comment]
I tested on mesa 22 and was working (anv, tigerlake)

I dont have my installation anymore, but it was a mesa issue

**Comment by davidbepo** [comment]
ok, just tested mesa-git, the crash remains the same

**Comment by jbeich** [comment]
Duplicate of https://github.com/yuzu-emu/yuzu/issues/7116 ?

**Comment by davidbepo** [comment]
@jbeich  it definitely seems so, but i want to know 2 things
1: was the issue reported to mesa(if not i can do it)
2: the bug you referenced talks about it being a mesa issue but a segfault on a missing capability is clearly an issue on yuzu side too

**Comment by jbeich** [comment]
> 1: was the issue reported to mesa(if not i can do it)

No because I wasn't sure it was Mesa fault and not Yuzu. Mesa change looks intentional and is generic to all Vulkan drivers. Unfortunately, documenting "steps to reproduce" that doesn't require one specific application like Yuzu is hard.

I'm also on FreeBSD, so reporting issues often requires filtering out unrelated noise to avoid confusing upstream.

**Comment by davidbepo** [comment]
closing as it was duplicate and #7747 fixes it
