### ISSUE TITLE
Kirby Star Allies unsupported texture cache format

### ISSUE THREAD

**Issue by FreddyFunk** [yuzu-emu/yuzu#7850]
Kirby Star Allies (version 4.0.0) seems to have an invalid texture format for the texture cache in the intro menu. 

Yuzu version: 7ad17ae39719d3dca80ea715e88c66ce7013ccea

[2298.335413] Debug <Critical> video_core/texture_cache/samples_helper.h:operator ():51: Unreachable code!
Invalid MSAA mode=15
[2298.335414] Debug <Critical> video_core\texture_cache\image_info.cpp:operator ():98: Unreachable code!
Invalid texture_type=15
[2304.435448] Debug <Critical> video_core\texture_cache\format_lookup_table.cpp:operator ():223: Assertion Failed!
texture format=127 srgb=false components={7 7 7 7}

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8005176/yuzu_log.txt)

**Comment by funtimeandrefoxy** [comment]
It also occurs with the demo and the base version of "Kirby and the Forgotten Land". It seems that when this error is mentioned in the output the game screen goes white for a second and then disappears for a few times.

**Comment by v1993** [comment]
All of those values look like interpreting the data incorrectly - 127 is not even close to any known texture format identifier.

**Comment by funtimeandrefoxy** [comment]
I may be making a big mistake (Because I know almost nothing about it), but this texture format will not be associated with the "
R8Snorm"? "https://docs.rs/wgpu/0.11.0/wgpu/enum.TextureFormat.html"

**Comment by v1993** [comment]
> I may be making a big mistake (Because I know almost nothing about it), but this texture format will not be associated with the " R8Snorm"? "[docs.rs/wgpu/0.11.0/wgpu/enum.TextureFormat.html](https://docs.rs/wgpu/0.11.0/wgpu/enum.TextureFormat.html)"

I sincerely appreciate your attempt, but this guess is off on many levels. Let's just say that it's certainly not that.

**Comment by v1993** [comment]
After messing with renderdoc and yuzu for a bit, it appears that this issue is directly related to #4639. Due to yuzu failing to recognize MSAA mode/texture format it ends up computing incorrect texture offset:

https://github.com/yuzu-emu/yuzu/blob/0b9ef3c0b844fbda14390c94bb6ddd37e3b36c90/src/video_core/texture_cache/texture_cache.h#L551-L554

This leads to DoF effect texture being offset by a single pixel, which is a lot due to purposefully low resolution.

It's still unclear what's the reason behind MSAA mode and texture format having odd values.

**Comment by v1993** [comment]
This seems to be fixed on current build and probably should be closed. Not hitting that assert anymore for me.
