### ISSUE TITLE
Zelda link's awakening: bowWow not rendering

### ISSUE THREAD

**Issue by A-w-x** [yuzu-emu/yuzu#7945]
![zz](https://user-images.githubusercontent.com/80461138/155805853-3bd2d61c-f986-4ec0-a1b1-6551e114ff49.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8144971/yuzu_log.txt)

**Comment by BigheadSMZ** [comment]
Not rendering using vulkan with a GTX1060 as well. Everything else seems to be fine.

**Comment by Timmy5942** [comment]
High GPU fixes it, but not the answer, GTX 1050 4GB TI is fine with high GPU but not RX 580 8GB Weird.

**Comment by Timmy5942** [comment]
After bit of testing, Its Not a graphics issue but a GPU or Core Timing issue. ^

**Comment by gidoly** [comment]
is it still persist?

**Comment by Timmy5942** [comment]
> is it still persist?

Yes, Only Setting High GPU fixes it, But slow down.

**Comment by OsoaGH** [comment]
same issue, gtx 1070 vulkan. sometimes doesn't render, sometimes looks like this:
![image](https://user-images.githubusercontent.com/33041004/188206419-32368188-f14e-4680-944e-84a5e8094992.png)
going inside the house it can look like this
![image](https://user-images.githubusercontent.com/33041004/188206478-5f270afd-888e-46a3-847a-0aa52efcd6a5.png)

**Comment by choseh** [comment]
same on Steamdeck (Vulcan)

**Comment by m0nk210** [comment]
> same on Steamdeck (Vulcan)

Same here. No Dog on Steam Deck.
Running the game untouched.  

If u guys also could fix that we would be able to Start the games thru emustation , that would be neat.

**Comment by Timmy5942** [comment]
Just a GPU issue maybe running too fast, Enable GPU High and it fixes it 100% but slows game, Enable too GPU Medium and BowWow stops working

**Comment by OsoaGH** [comment]
for me if you turn gpu high on and then back to medium it will fix bowwow until he is unloaded.

**Comment by Timmy5942** [comment]
EDIT: Issue seams to be around "use asynchronous GPU emulation" when disabled slow down game play bowWow rendering fine

When Asynchronous is un Use seams to be around Shader issues, In Yuzu Coding.

**Comment by Hidekikun** [comment]
Did anyone find a fix for this or is slowing down the only option atm?

**Comment by m0nk210** [comment]
Best solution i found was in yuzu under GPU adv. settings the accuracy setting high - no alow downs whatssoever on my end.

**Comment by Alxand13** [comment]
Using an AMD R5 4500 (stock) with 16GB RAM set at 3200MHz +RX6400 clocked at ~2000MHz here.

Trying this tittle in its 1.0.1 updt with Vulkan in the latest Yuzu build (1345 from feb 19) and issue persist - same happens when running "v1.0.0".

With GPU set to "High" in the app settings everything looks fine, but theres A LOT of slowdowns - worse than other emu in the same HW running this game, that only slows in the first village or wherever you go when you have Bowow following you; on Yuzu looks to have micro stuttering happening everywhere at everytime with this setting.

If GPU is set to "Normal" the thing runs better than fine and game is smooth at anyplace, but every Bowow gets messed textures and sometimes exploding vertexes over the whole screen (need to explore a bit to see if theres other models with the same effect).

When theres one of the before mentioned models on screen, changing from "Normal" to "High" then going back to normal looks to solve the issue despite it coming back when the model need to be reloaded (which the game looks to do everytime a model was out of screen)...

Maybe modding something in Yuzu GPU settings like an "hybrid mode" to make it peak a couple seconds in GPU high settings when areas/models are loaded then runs with normal setting after that could bypass this kind of issue since this looks to be the best solution to the problem now - despite needing to be manually done by clicking in the botton left corner of the screen at windowed mode.

**Comment by cnrtks** [comment]
YUZU > Configure > Graphics Advanced > Accuracy high (no more corrupted chomp chains but now game runs slow)
to fix:
Install 60fps mod (its on yuzu website just put it in the right directory)
install CryoByte33 steam deck utilities via github use the recommended settings
install power tools via decky loader and open it and disable SMT
works perfectly so far, those last 2 steps i did at the same time and never checked which one actually fixed the issue. maybe just disable the SMT and see if thats enough without installing the steam deck utilities from cryobyte

**Comment by gidoly** [comment]
should fixed on both normal and high accuracy on lastest ea and mainline
