### ISSUE TITLE
Crashes on Minecraft 1.12.1

### ISSUE THREAD

**Issue by ThePixelGamer** [yuzu-emu/yuzu#7993]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8202860/yuzu_log.txt)

Launching Minecraft with version 1.12.1 installed crashes yuzu, I'm also unsure on how to provide a backtrace (if that would even be helpful)

**Comment by ThePixelGamer** [comment]
Here's the important part of that log, with 900 issues I figured I should send this to be glanced at. 
```
[  26.486436] Core <Warning> core\hle\kernel\hle_ipc.cpp:WriteBuffer:267: skip empty buffer write
[  26.833138] Service <Info> core\hle\service\sockets\bsd.cpp:SocketImpl:475: New socket fd=0
[  26.838633] Service <Info> core\hle\service\sockets\bsd.cpp:SocketImpl:475: New socket fd=1
[  26.839790] Debug <Critical> core\hle\service\sockets\bsd.cpp:operator ():572: Assertion Failed!
```

**Comment by ThePixelGamer** [comment]
Did some testing, seems to be calling accept with 127.0.0.1 and for some reason both BufferDescriptorB and BufferDescriptorC have their size bits set to 0 so maybe unrelated to bsd.cpp? Still getting acquainted with yuzu so I'll have to see if there's any hints in the rest of the log.

**Comment by ThePixelGamer** [comment]
Updated log using @v1993's PR
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8252963/yuzu_log.txt)

The ``Service <Warning> core\hle\service\sockets\bsd.cpp:Select:168: (STUBBED) called`` block at the end continues to appear and yuzu seems to be stuck on it

**Comment by german77** [comment]
bsd is networking. Try disabling the network interface in yuzu. It might be waiting to connect to a server

**Comment by Docteh** [comment]
For connections going out of the machine you can stub out by having the checks for a valid and working networking configuration all fail. 

I don't believe that'll work with 127.0.0.1 as that is localhost. 

```
[  75.843373] Debug <Critical> core\hle\service\sockets\bsd.cpp:operator ():668: Assertion Failed!
Unimplemented code!
[  75.843414] Debug <Critical> core\hle\service\sockets\bsd.cpp:operator ():705: Assertion Failed!
Unimplemented optname=1
```
Line 668 is inside a function `BSD::SetSockOptImpl`
https://github.com/yuzu-emu/yuzu/blob/f55af65e8214f50792d967e481ab612b33c7c3b2/src/core/hle/service/sockets/bsd.cpp#L668

I'm doing some reading up on BSD sockets right now, and it seems like the levels are defined in `#include <netinet/in.h>` on Linux platforms. 

For Windows it looks like different files should have a reference to defines such as `IPPROTO_TCP`
https://github.com/yuzu-emu/yuzu/blob/4a77ceb1510f3c97abcf739a893a4d0f2f5bba6e/src/core/network/network.cpp#L13-L27

Unofficial glibc mirror, https://github.com/bminor/glibc/blob/master/inet/netinet/in.h Linking that to explain why my guesses on what the `level` is.
```
IPPROTO_IP = 0
IPPROTO_TCP = 6
IPPROTO_UDP = 17
```
These numbers are specified in `netinet/in.h`. I found a mirror of glibc on github, [linking its netinet/in.h](https://github.com/bminor/glibc/blob/master/inet/netinet/in.h) for reference. But it can also be available at like `/usr/include/netinet/in.h`


I think in the `BSD::SetSockOptImpl` function the next step is to log what the passed `level` is when its not `0xffff`. My guess is that its  0, 6, or 17

Oh, the assertion at line 705 is probably part of the same call to `BSD::SetSockOptImpl`

Instead of like 668 `    UNIMPLEMENTED_IF(level != 0xffff); // SOL_SOCKET` I wonder if this would be informative.
```
    if (level != 0xffff) { // SOL_SOCKET
        UNIMPLEMENTED_MSG("Unimplemented setsockopt level={} optname={}", level, optname);
        return Errno::SUCCESS;
    }
```

Is this crash from just asking Minecraft to load, or is it trying this networking stuff only when you're trying to play single player?

**Comment by german77** [comment]
From my test the game wants to connect to Internet no matter the situation

**Comment by ThePixelGamer** [comment]
@Docteh More is required to get the game working and I already have a build that works. Just gotta improve it and see if it can be made a PR.

https://github.com/yuzu-emu/yuzu/blob/f55af65e8214f50792d967e481ab612b33c7c3b2/src/core/network/network.h#L52-L56

**Comment by viviy228** [comment]
> @Docteh More is required to get the game working and I already have a build that works. Just gotta improve it and see if it can be made a PR.
> 
> https://github.com/yuzu-emu/yuzu/blob/f55af65e8214f50792d967e481ab612b33c7c3b2/src/core/hle/service/sockets/sockets.h#L40-L45

@ThePixelGamer I am trying to load Minecraft and see the same error. Have you got it to work in the end? TIA
