### ISSUE TITLE
Mysterious Nintendo vulkan extension

### ISSUE THREAD

**Issue by LifeIsStrange** [yuzu-emu/yuzu#8131]
Slightly before launching the switch to the market, Nintendo, in collaboration with Nvidia created a Vulkan extension:
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_NN_vi_surface.html
So I was wondering wether understanding it could help the vulkan renderer of yuzu?

Feel free to close this issue if judged irrelevant

**Comment by v1993** [comment]
I wouldn't call it mysterious in the slightest - it's simply an interface for applications to allow creating video output surface when utilizing Vulkan API. It exists because native rendering surface creation mechanism is platform-specific - there are such extensions for Windows, MacOS, X11 and Wayland, so Nintendo also needed one for Vulkan support on their system.

**Comment by LifeIsStrange** [comment]
Great explanation! So that doesn't seem to be useful for Yuzu.
