### ISSUE TITLE
All games crash at “Launching...” from EA 2687 onward

### ISSUE THREAD

**Issue by MisakaMikotoDolphin** [yuzu-emu/yuzu#8247]
Beginning with Yuzu **EA 2687 (8b7c1ed)** and **mainline 991 (32dceeb)**, all games crash on launch. (I tried every release from EA 2687/ML 991 on, and all of them crash.)

I’m running Yuzu with the latest firmware and keys on **Windows 7 Pro x64**, with 32 GB of RAM and an RTX 2060 using the latest Nvidia drivers.

> _I realize it’s possible this is an incompatibility with Windows 7, such as Cemu recently experienced with DirectInput for Windows 7 and Linux until the devs tweaked the code change in question. And if it is, and Yuzu won’t function on Windows 7 in future, then I’ll just stick with 2685._
> 
> _But I figured it’s worth asking in case the Yuzu team is still fine keeping Win7 compatibility, much like how Cemu still lists Windows 7 as its minimum sysreq. Obviously it’s not necessarily part of the project aim, but continuing to allow use of an older OS is a nice complement to the broader emulation goal of preserving the operability of console hardware as it ages. I’m grateful for it, anyway!_
> 

Anyway:

Through EA 2685/ML 990, games launch as normal, whether launched from the command line or the gamelist.

Beginning with EA 2687/ML 991, **Yuzu loads shaders normally, then shows the “Launching...” text for a split second and immediately crashes silently, with no error.**

A reboot did not fix the issue, but reverting to EA 2685/ML 990 does, every time.

**Comment by pacoa-kdbg** [comment]
@MisakaMikotoDolphin  can you provide a log ?

**Comment by MisakaMikotoDolphin** [comment]
Sure, here’s the log files created by a failed launch in 2687:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8547603/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/8547604/yuzu_log.txt.old.txt)

**Comment by MisakaMikotoDolphin** [comment]
And here’s the log file created by a successful launch in 2685:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8547608/yuzu_log.txt)

**Comment by german77** [comment]
EA builds are a bit meaningless for us. Since tracking changes it's not easy. If you are able to test on mainline it will be appreciated.

**Comment by MisakaMikotoDolphin** [comment]
Oh, sure, no problem—I’ll check and see. Sorry about that!

**Comment by MisakaMikotoDolphin** [comment]
Same issue, beginning with mainline 991 (32dceeb).

Here’s the logs for a failed launch using ML 991:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8547629/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/8547630/yuzu_log.txt.old.txt)

**Comment by MisakaMikotoDolphin** [comment]
Here’s the log for a successful launch with ML 990:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8547631/yuzu_log.txt)

**Comment by german77** [comment]
Interesting. 991 updated dynarmic it has a very high change it doesn't support windows 7.  @merryhime is this expected or some kind of bug?

**Comment by merryhime** [comment]
Would not be expected, no.

**Comment by german77** [comment]
As explained by the issue 8386 yuzu doesn't support windows 7 or 8 anymore

**Comment by o5k** [comment]
> [Which platforms does yuzu support?](https://yuzu-emu.org/wiki/faq/#which-platforms-does-yuzu-support)
yuzu is actively tested and supported on various 64-bit versions of Windows (**7 and up**) and Linux. macOS is no longer supported due to Apple deprecating OpenGL.

![hrmm](https://user-images.githubusercontent.com/52112045/171266869-a657d08e-9530-4504-9519-80e6ad19cb4d.png)

**Comment by MisakaMikotoDolphin** [comment]
Every other emulator I use, including those in active development, still functions on Windows 7; it’s disappointing to see the Yuzu team be the one outlier that is fine outright preventing users from even attempting to run its emulator on an operating system that is still installed (as of last month) on an eighth of desktop computers worldwide.

**Comment by MisakaMikotoDolphin** [comment]
![won't be fixing it](https://user-images.githubusercontent.com/13497669/171306169-87d0c1a2-89f1-4a02-a7c7-a69518fcc852.png)

That’s good to know. I built my own Windows 7 installation media with slipstreamed NVMe and custom USB 3.1 drivers so I can continue using Windows 7 into the foreseeable future, so I don’t plan to switch my OS in the foreseeable future; so I’ll just stick with ML 990/EA 2685 and drop the Patreon as no longer being of any use to me. Being able to use future versions of Yuzu isn’t worth the requirement of switching to Windows 10.

**Comment by Dogway** [comment]
Yeah, it's today's problems with current society, arrogance and self indulgence.
They will even try to make you believe Windows 8.1 is EOL, and if not that it's barely used, an excuse they couldn't use with Win7, and all because there are no balls to apologize for admitting one owns faults.

I don't know how many projects yuzu has, Hades, Gaia, ART, Y.F.C.... yet for dropping Win7 and Win8.1 support they do it in this clunky and shadowy fashion.

Now the ~~dic...~~ mods can lock this issue as well.

**Comment by goldenx86** [comment]
Using Linux doesn't bite.

**Comment by lat9nq** [comment]
From the perspective of a guy who works mostly on the Linux side of things, reading this thread has been rather curious to me. I get that moving operating systems is at least inconvenient, and in the case of Windows you're moving between closed source OSes here. Even on the open-source side of things, I mean there's a reason I switched from Arch Linux to Fedora, right? Things don't move around as fast over here, so I can somewhat expect things to be consistent from day to day.

So what happened here? Mostly a mix of miscommunication and lack of resources. I think the dev that "broke" it did so on a separate project, and then when that made its way into yuzu it was absolutely unexpected for us, too. Myself I didn't even catch wind of this until a few days ago (maybe that was my insomnia day....) So between that and none of the developers I know of even using these old Windows installs, I don't think it should be entirely unexpected that something like this should happen.

I think also that the nature of this issue is a bit unfortunate, being that it affects Windows 7 which is out of date (I see Windows 8 mentioned here? can't tell if that's also affected, but you'll see in a sec why I don't think they're out of the water either). Windows 7 is EOL, so they aren't getting security updates (meh), but more importantly neither they nor Windows 8 are getting graphics driver updates. So this was going to happen sooner or later, given that yuzu is an experimental emulator with things moving left and right all the time. Maybe this is a bit soon? Meh, I think if we fix this one issue we'll start playing whack-a-mole soon enough. And given that we don't use Windows 7 or 8 here and all of us contribute on our free time, I think we just want to stick to what's supported.

So what is there to do? Well, personally I switched to Linux the moment Windows XP told me it's time to "switch to a modern operating system." If something on our end breaks there you can always ask me about it. But you don't have to do the same thing I did. 990 (or maybe rather Mainline 960) still works and ain't going nowhere. Also, this is open-source software: the issue is "closed" but doesn't mean you can't go and fix the issue. We're always looking for contributors.

Sorry that you all are upset. We really do try to be respectful but maybe it doesn't always come across that way.
