### ISSUE TITLE
Super Mario™ 3D World + Bowser’s Fury (010028600EBDA000) Local multiplayer issue

### ISSUE THREAD

**Issue by mishailovic** [yuzu-emu/yuzu#8303]
I properly configured the "Network" tab in Yuzu settings, still when I'm trying to create a room this message pops out. Maybe there is any way how can I fix that?

![image](https://user-images.githubusercontent.com/41520056/166649220-2508c413-41d8-47d3-bba8-abee4fd6095a.png)
![image](https://user-images.githubusercontent.com/41520056/166649376-3f6e4c31-9429-4c04-8c51-078190039010.png)

**Comment by Docteh** [comment]
My understanding is that the current implementation is for LAN, but I guess the UI doesn't mention that... 🤔

**Comment by mishailovic** [comment]
> My understanding is that the current implementation is for LAN, but I guess the UI doesn't mention that... 🤔

Just pasted wrong screenshot, my bad. Anyways I chose the "Local Wireless Play"

**Comment by Docteh** [comment]
I meant LAN like ethernet

For example Mario Kart 8 deluxe supports Ethernet LAN https://www.gameskinny.com/purxx/how-to-set-up-your-own-mario-kart-8-deluxe-lan-party

![image](https://user-images.githubusercontent.com/190571/166652287-e34f4d80-a324-4573-b935-fc897c0419d0.png)

For Local Wireless the console can take direct control of the wireless and do  what it wants. Not sure how happy Windows or Linux would be with an application wanting to take control of the wireless networking chip.

**Comment by mishailovic** [comment]
I see, thanks for your reply! Will try some workarounds such as VPN or Ethernet as you mentioned.

**Comment by G-Spawn** [comment]
> I see, thanks for your reply! Will try some workarounds such as VPN or Ethernet as you mentioned. Maybe Yuzu devs might implement something like virtual internet adapter which will act like a middle part in the Switch's network process?

Workarounds won't achieve much for unimplemented functions

In future we will introduce LDN (Local wireless) For now this is expected result since it is unimplemented. We only offer lan play atm for lan play capable games. http://www.lan-play.com/games-switch eg the top list of games (known to work are mk8d, arms, splatoon 2, and Pokken )

If you want to do local multiplayer in sm3dw+bf you can just do split screen and setup multiple controller to same emu. Parsec also works for this.

Closing for now. Stay tuned in future we will provide progress report / more info once LDN is going to be a thing here.

**Comment by mishailovic** [comment]
Thanks a lot @G-Spawn! Really looking forward to LDN.

**Comment by G-Spawn** [comment]
Np and same :3 Much hype hehe.
