### ISSUE TITLE
[bug] Yuzu 1036 not running on Linux

### ISSUE THREAD

**Issue by varlesh** [yuzu-emu/yuzu#8396]
Standalone version not running: [yuzu-linux-20220530-a526692c2.tar.xz](https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-1036/yuzu-linux-20220530-a526692c2.tar.xz)
On Terminal have errors:
```
./yuzu
./yuzu: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./yuzu)
./yuzu: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./yuzu)
```
Previous versions worked fine.
OS: Ubuntu 20.04
libstdc++6 10.3.0-1ubuntu1~20.04

**Comment by varlesh** [comment]
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_1.3.10
CXXABI_1.3.11
CXXABI_1.3.12
CXXABI_TM_1
CXXABI_FLOAT128
```

```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by lat9nq** [comment]
This is not a bug, given that we ship an AppImage and a Flatpak. As you've pointed out, the issue here is that your Linux distro does not ship libraries as recent as yuzu requires, in this case libstdc++ 11.

I recommend you switch to using the AppImage or Flatpak. A less recommended route be going to https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test, getting GCC 11 from there, and then setting your LD_LIBRARY_PATH to include the libstdc++ that it installs. (Or, I guess extract libstdc++ from the AppImage and use that.) This only gets you as far as until yuzu requires another library that is too old with Ubuntu 20.04, hence my previous recommendations.

**Comment by varlesh** [comment]
i know about LD_PRELOAD and Appimage, but now it's not comphortable use with scripts ()
