### ISSUE TITLE
Yuzu crashing on game startup

### ISSUE THREAD

**Issue by Bryan9995** [yuzu-emu/yuzu#8589]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9119921/yuzu_log.txt)

The 1090 update seems to be causing me issues. When i try to load Animal Crossing: New Horizons it loads the load screen but the actual game crashes. 

Anyone know of a fix for now, or do I have to wait for another update?

Edit: I apologize, i didn't realize the previous log was empty.

**Comment by Morph1984** [comment]
The log you provided is empty, can you provide a new one?

**Comment by Bryan9995** [comment]
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9119917/yuzu_log.txt)

I apologize about that, It was populated when i opened it last.

**Comment by Bryan9995** [comment]
I had updated the log file from my previous.

**Comment by OZtistic** [comment]
I can see a couple of issues in your log file.
This would be best dealt with in the Discord.
However I will highlight what I see as immediately wrong
You are using Single Core (use Multi Core)
Turn off Async Shader Building (there is no need for it)
Use NVidia 512.95 video driver instead of 515.x+ (it is known to cause issues)
Apply the latest game update for the game
If you still have issues after this please join the Discord
https://discord.gg/u77vRWY

**Comment by Bryan9995** [comment]
> I can see a couple of issues in your log file. This would be best dealt with in the Discord. However I will highlight what I see as immediately wrong You are using Single Core (use Multi Core) Turn off Async Shader Building (there is no need for it) Use NVidia 512.95 video driver instead of 515.x+ (it is known to cause issues) Apply the latest game update for the game If you still have issues after this please join the Discord https://discord.gg/u77vRWY
> 
> GitHub is not a Support channel


I will hopefully see you on discord then and this issue can be fixed.
