### ISSUE TITLE
Vulkan memory leaks in any game.

### ISSUE THREAD

**Issue by OmarRod1314** [yuzu-emu/yuzu#8693]
I've been using this emulator since a while as I can, enough to get far in SMO, SSBU... Unfortunately, no matter the game or configuration, any game will unavoidably crash in loading screens or random compilation, with no errors. I checked the logs, and they cut midway whenever these crashes happen... So no errors are reported. These are my specs, they aren't ideal but demanding games run well as long as they're not crashing, so i'm sure it's not a hardware issue. Also, I tried to run it on Linux with the same API, and for my surprise... It ran perfectly, on par with Windows but no crashes, so that's one thing to have in mind.

Windows 10 21H2 (x64)
Intel Core I3 3240.
8 GB RAM 1600mhz (In dual channel)
AMD Radeon R5 240 1 GB.
1 TB HDD (Western Digital)
Yuzu mainline 1115 (happening since a few)

Here are the logs, with no errors at all. I can't reproduce the bug in most games, as it's completely random, only in Metroid Dread (on the transition before the first EMMI cutscene) but still no errors. I'd like to use OGL as well, but this card is legacy GCN and the newest version with the performance fixes is unavailable. Something's *very* wrong with Vulkan's memory management here, and I'd like to know why.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9229713/yuzu_log.txt)

**Comment by G-Spawn** [comment]
Generally since you only have 7-8gb usable physical memory, you should consider setting a much larger windows pagefile (20-25gb). That should help for vulkan stability vs keeping windows set to auto.

**Comment by OmarRod1314** [comment]
> Generally since you only have 7-8gb usable physical memory, you should consider setting a much larger windows pagefile (20-25gb). That should help for vulkan stability vs keeping windows set to auto.

I had to do that, seems like it worked but it's not a perfect fix still. Is there any awareness of a memory leak for Vulkan in Windows?

**Comment by G-Spawn** [comment]
Yes.

**Comment by G-Spawn** [comment]
The issue is also due to your hardware as well. Yuzu relies heavily on CPU & decent memory capacity-speed.

**Comment by G-Spawn** [comment]
I would be content with how it runs atm considering most hardware that predates the console by 5+ years fares very poorly here.

**Comment by goldenx86** [comment]
For that hardware, use Linux. We don't target its outdated Windows drivers any more, and we require a minimum of 2GB of VRAM.

**Comment by OmarRod1314** [comment]
I'd assume the lack of VRAM is playing a part, too. I'm wondering if a similar Nvidia card (GT 730 DDR5) fares any better, as long as it's the 2 GB variant.

**Comment by DAOWAce** [comment]
I think the core of the issue is still relevant regardless of users' system specs.  Unfortunately, it's not just limited to Vulkan from reading numerous issue reports here.

Yuzu has been crashing in battle for me and a friend playing FE3H, similar to this; absolutely no visible errors in the log, it just cuts out abruptly as Yuzu crashes.  They have a more mainstream budget build (i5 10400, 3060 Ti, 16GB RAM), I have a 5950x, 4090 and 64GB RAM.

Trying to look through github about it, finding not really much resolution to the issue, but just to list a few related:

https://github.com/yuzu-emu/yuzu/issues/6290
https://github.com/yuzu-emu/yuzu/issues/6080
https://github.com/yuzu-emu/yuzu/issues/6030
https://github.com/yuzu-emu/yuzu/issues/7297
https://github.com/yuzu-emu/yuzu/issues/9599

Most issues I find are closed, but with no actual resolution to the crashing issue.  Some of the crashes had legitimate errors and those got fixed (mostly), but the completely random Yuzu hard crash with no error, that still remains.

This was linked in one of them: https://www.patreon.com/posts/new-feature-35856792

2 years old so things are different now, but I can say that upon initial load of the game, the RAM usage is already **9GB**.  Loading into battle, the commit size goes up to 10GB.

Differences with older versions of yuzu (ie from May 2022) is that when stopping the emulation, it takes a long time (~10 seconds) while showing "stopping software". In the older version this was instant.

And then Yuzu is still eating 6GB of RAM (3GB commit) sitting on the menu afterward.  A fresh start of Yuzu only uses 144MB.  It is not releasing most of the memory.  In comparison to the old version, it's sitting at 8GB, but only 422MB commit.  I'm not a developer so I don't understand the real impact of this behavior.

Having said this, I have not attempted to emulate any other game besides FE3H since returning to emulation after 2¾ years, so I cannot make a judgement on if it's a game specific problem or Yuzu itself.


Regardless, it seems I have to look into the discord in order to check for active discussion of this problem, but I just want to post here for now, maybe open a dedicated issue for it if I still can't find something more relevant than this, as it's extremely demoralizing losing hours of your time to crashes, especially when there's no symptoms or evidence of any errors.
