### ISSUE TITLE
yuzu crashes when running multiple instances

### ISSUE THREAD

**Issue by hindexfindex** [yuzu-emu/yuzu#8708]
hello, if there any way to fix this by myself, this is just a simple question, or is there anyway to fix this myself, if there is a fix for this please let me know

**Comment by german77** [comment]
Yuzu uses configuration files. If an instance of yuzu is already using them the second one would not be able to load them properly. Use portable builds if you want multiple instances of yuzu on the same PC

**Comment by Docteh** [comment]
Are the instances using the same data directories for like logs and and nand? 

I have multiple instances and of yuzu open all the time, but I'm only using one at a time to play a game.

**Comment by hindexfindex** [comment]
how to get portable build?

**Comment by german77** [comment]
Create an folder called "user" where yuzu.exe is located

**Comment by hindexfindex** [comment]
it only crashes when i play a game

**Comment by german77** [comment]
Take into account Yuzu is resource intensive. You are limited to what your PC can handle. Here I ran out of ram and almost maxed out my gpu so I can't run a third instance. Also you may need a copy of the game for each instance because they also get constantly used. For further help ask on discord. This is not a support forum 
![image](https://user-images.githubusercontent.com/5944268/182645803-31959a4c-b001-4609-b767-7bcdd98a3176.png)
