### ISSUE TITLE
why does yuzu work on virtual memory

### ISSUE THREAD

**Issue by hindexfindex** [yuzu-emu/yuzu#8717]
hello, from what mst people, are what some people may know is that yuzu only works on memory depends on how much it is, i was wondering if there is a fix for this, or just leave it how it is, because i might wanna do lan splitscreen, with yuzu and put controllers to eatch instance of yuzu, but for some reason one of them crashes, is there nay faq on why yuzu runs on maximum memory, or just anythign that has to do with this yuzu problem please let me know

also here is a video

https://user-images.githubusercontent.com/107736543/182841008-aa4ecc36-b684-433a-9a2f-368271de3f6c.mp4

**Comment by FernandoS27** [comment]
in order to emulate the virtual space of each application in the switch. we must reserve a large chunk of virtual memory, as we use the Host MMU to emulate the Guest MMU. You can avoid this at the cost of some performance by disablig Host MMU CPU optimization on the Debug tab within configuartion (CPU debug must be on).

**Comment by hindexfindex** [comment]
idek know if it worked. im looking for settings where i can load any game with isntance i want without virtual memory

**Comment by german77** [comment]
Fernando just told you how to disable the use of virtual memory. Set the `cpu accuracy to Debug` then disable `Host MMU CPU optimization` under `general->debug `
