### ISSUE TITLE
[Feature Request]Customize Discord Rich Presence

### ISSUE THREAD

**Issue by widardd** [yuzu-emu/yuzu#8725]
Instead of just "yuzu" on the forefront, with what you're playing visible only upon inspection, I would want to have it the other way around.

**Comment by CaptV0rt3x** [comment]
Our implementation is actually consistent with how other "similar" applications use rich presence. 

For example, with Spotify - it shows up as "Listening to Spotify", rather than "Listening to <Song>", and the actual song details are visible only upon inspection.

Also, to the best of my knowledge, many other emulators also follow this style.

**Comment by FearlessTobi** [comment]
"Yuzu" is the application name that is always displayed by Discord when using Rich Presence.
Since we can't change this, I'm going to close this issue.

**Comment by widardd** [comment]
> "Yuzu" is the application name that is always displayed by Discord when using Rich Presence. Since we can't change this, I'm going to close this issue.

That's not try,  you can customize and show whatever you want via Discord. Yuzu is applying this, not the other way around.

**Comment by merryhime** [comment]
Discord fixes the application name and icon to a ClientID.

I would suggest using the various Custom Presence apps avaliable, just like you recommended yourself, to understand this is a discord limitation.
