### ISSUE TITLE
Bug Pokemon Sword e Shield Vulkan AMD

### ISSUE THREAD

**Issue by rgbarros120** [yuzu-emu/yuzu#8835]
They still haven't fixed this bug, it's complicated huh. I've been playing this emulator for a while and I'm still having the same bugs. Keyed up. Just remembering that this bug is only in the vulkan amd api and not in the amd opengl. It's been about three and a half years with this bug and no one can fix it. You have to review this code.

My Specs: Radeon RX 560 OC 4GB; RYZEN 5 1600; 16GB DE RAM
DRIVER 22.8.1
![Bug Amd Vulkan](https://user-images.githubusercontent.com/73244003/187555079-63ec1543-6e90-4e70-b7ad-71ee22718c98.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9457026/yuzu_log.txt)

**Comment by pacoa-kdbg** [comment]
This issue can be closed as is it duplicated of [8576](https://github.com/yuzu-emu/yuzu/issues/8576), 
Please stop creating issues, it is better to just update the prior one.

btw, feel free to review the code yourself and try to provide a solution to the issue.

On the meantime, install latest AMD driver and play happily with openGL backend

**Comment by rgbarros120** [comment]
> This issue can be closed as is it duplicated of [8576](https://github.com/yuzu-emu/yuzu/issues/8576), Please stop creating issues, it is better to just update the prior one.
> 
> btw, feel free to review the code yourself and try to provide a solution to the issue.
> 
> On the meantime, install latest AMD driver and play happily with openGL backend

The point is not to get in trouble. And yes you guys stop focusing a little bit on updating controls and focusing on the parts of graphical corrections.

**Comment by pacoa-kdbg** [comment]
I am not part of the development team, just another user.
If the team focuses on updating controls it is because there is someone with expertise (or willing to learn and put time) into it.

Remember that yuzu is an open source project with, currently, no full time devs so whatever the devs decide to implement/improve it is because they are motivated or have the skills to do it.

Anyways, github is not the place to discuss this.

Still, this issue can be closed as it is duplicated.

**Comment by gidoly** [comment]
this issue happens due to amd not supports certain formats on their driver.
and as paco mentioned this issue is duplicate with existing one. i will close due to that reason
