### ISSUE TITLE
Debug opcode without cheatengine's DBVM on yuzu

### ISSUE THREAD

**Issue by HIRO0132** [yuzu-emu/yuzu#8879]
I want to use cheatengine with YUZU, but I can't analyze opcode access unless I use DBVM mode
DBVM mode is unstable and has broken my SSD twice in the past
Is there a way to make this accessible to yuzu's game opcode with a regular debugger (VEH or windows debugger)?
If not, can I request a feature?

**Comment by merryhime** [comment]
VEH unfortunately has priority over SEH which is why things break.
Try disabling fastmem entirely, like so:
![image](https://user-images.githubusercontent.com/8682882/189519621-e0632dae-2736-4d4f-972d-2c904cb4b640.png)
![image](https://user-images.githubusercontent.com/8682882/189519624-4f9179fe-4038-4a00-ab45-5c4e9edea807.png)

**Comment by HIRO0132** [comment]
OK. thanks for the reply
