### ISSUE TITLE
[Request] Separate Shaders for different gpus on the same machine.

### ISSUE THREAD

**Issue by LazyBunny** [yuzu-emu/yuzu#8995]
Quoted from discord:
_Lazy Bunny Kiera#5260 — Today at 5:34 AM
Does Yuzu create separate shaders depending on which gpu or even which driver version you're using?
I have 2(technically 3) different GPUs. Intel Xe, RTX 3060TI eGPU, and an RX570 mini-eGPU(that I never use.)
If i use OpenGL with the 3060Ti and then switch to intel Xe, will it replace the shaders, or compile new shaders separately?
So far I've been using OpenGL on the 3060Ti and Vulkan when using the Intel Xe to keep them separate._

I was informed that they are not separate and instead replace. So my request is that for people that use separate GPUs and possibly even driver versions, to have the non-transferable shaders be made separate. So any shaders compiled when I use my massive 3060Ti eGPU won't be overwritten when I switch to my Intel Xe iGPU or AMD RX570 travel eGPU.

Many PCs and especially laptops have multiple GPUs, usually an iGPU and a dedicated GPU. So being able to keep them separate would be nice so we don't need to recompile everything we swap.

Suggested "Fix":
I understand this is pretty niche, but I'm hoping it would be relatively easy to implement. Yuzu already checks what GPU you're using. So have it make a folder with that gpu's Vendor/Device IDs. PCI\VEN_10DE&DEV_2489 for an RTX 3060Ti for example. And then load shaders from that folder when that GPU is selected. 

My current workaround.. I use OpenGL with my 3060Ti and Vulkan with my Intel Xe. But Vulkan can be hit'n'miss. But this has been the only way I could keep the shaders separate so far.

Thank you.

PC Specs:
GPD Win Max (2021)
CPU: Intel i7 1195G7 w/ Intel Xe iGPU
Internal SSD: SK Hynix P31 2TB, + Multiple external storage devices.
RAM: 16GB LPDDR4x 4267mhz
Main eGPU: Gigabyte RTX3060Ti OC in Razer Chroma eGPU enclosure for Desktop Mode
Travel eGPU: AMD RX570 Sonnet Breakaway Puck
Desktop Mode: LG 25" 2560x1080 75hz LCD, BT KB, USB Redragon Mouse.

**Comment by liamwhite** [comment]
This is a misunderstanding of how yuzu caches shaders. The generated SPIR-V/GLSL are not cached, and what is instead cached is the guest state that is used to generate the host shaders (because things like the host features can change on a run-by-run basis depending on the drivers in use).

This means that shaders inside the same API are _always_ transferable, because they are always recompiled to match what the host expects on every game launch. There is no way to change this. Currently yuzu does keep a separate cache of guest shaders depending on if you are using OpenGL or Vulkan but I intend to unify these in the future as there is no real reason for them to be kept separate.

If you measure a difference in compilation performance on the same API between different devices, this is likely the impact of your GPU driver, which also has a caching layer to speed up recompilation of shaders, and that affects recompilation performance on a per-GPU basis.
