### ISSUE TITLE
failed to register appimage in system via libappimage

### ISSUE THREAD

**Issue by Hadrianneue** [yuzu-emu/yuzu#9268]
Recent yuzu-mainline builds going back to September are presenting this issue.

[yuzu 1180](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1180) build is the latest one that doesn't present this issue however its also not working properly, it doesn't trigger the integration dialog it just straight up runs yuzu.

Beginning with [yuzu 1181](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1181) it shows this message 'failed to register appimage in system via libappimage', it runs fine though but it doesn't integrate.

Operating System: Manjaro Linux
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7
Kernel Version: 6.0.8-1-MANJARO (64-bit)
Graphics Platform: X11

**Comment by DomiStyle** [comment]
The cause for this is the "incorrect" symlink to the .desktop file that yuzu uses.

The current symlinks look like this:

```
org.yuzu_emu.yuzu.desktop -> ./usr/share/applications/org.yuzu_emu.yuzu.desktop
org.yuzu_emu.yuzu.svg -> ./usr/share/icons/hicolor/scalable/apps/org.yuzu_emu.yuzu.svg
```

It should look like this:

```
org.yuzu_emu.yuzu.desktop -> usr/share/applications/org.yuzu_emu.yuzu.desktop
org.yuzu_emu.yuzu.svg -> usr/share/icons/hicolor/scalable/apps/org.yuzu_emu.yuzu.svg
```

Notice the `.` at the beginning of the link. Removing the links and recreating them without the dots fixes the parsing with libappimage and allows the AppImage to be started or integrated.

Not 100% sure if this is a bug with yuzu or libappimage/appimaged since the symlink is valid in Linux.

**Comment by EeveeEuphoria** [comment]
I'm hoping this pull request gets accepted soon, since I'm experiencing the exact same issue.

**Comment by firefloc** [comment]
same issue here
