### ISSUE TITLE
FullScreen Crash

### ISSUE THREAD

**Issue by JuanCarlosM1** [yuzu-emu/yuzu#9506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1282

### Description of Issue

When I try to use the Full Screen mode the Yuzu crash.

### Expected Behavior

Go to Full Screen Without any problems.

### Reproduction Steps

I found that the bug only occurs when option to pause the emulation when the window is in the background

https://user-images.githubusercontent.com/64020519/209479610-8455869d-8e7a-420f-a733-b9e80221fda5.mp4

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10300521/yuzu_log.txt.old.txt)

### System Configuration

CPU: Ryzen 5 5500u
GPU/Driver:21.40.52.09-220721a-381556C-Lenovo
RAM: 8gb
OS: Windows 11

**Comment by goldenx86** [comment]
Update your GPU driver manually to the latest release, 22.11.2, and if possible add more RAM, the iGPU is only getting 512MB of buffer.

**Comment by huzki1998** [comment]
I also have the same problem   CPU:Ryzen 7 5800u.
After I installed Hwinfo and Rivatuner Statistics Server
Whenever I switch yuzu from window mode to fullscreen or fullscreen to windows
Yuzu will always crashed and stuck, even if I closed Hwinfo and RTSS

**Comment by RokkumanX** [comment]
As mentioned in the https://github.com/yuzu-emu/yuzu/issues/9550 issue, the problem that's causing this is because of the Pause emulation when in background setting being checked/on.

If you turn it off, fullscreen works as it should.

Tested this with EA 3303.

There is something that have changed in that setting because older versions EA 3216 and Mainline 1277 is working great with the setting on.
