### ISSUE TITLE
Per-game fps limiter.

### ISSUE THREAD

**Issue by piau9000** [yuzu-emu/yuzu#9517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A built in and per game fps limiter, that can helps in cases where reaching 60 fps is not always possible. 

### Why would this feature be useful?

Some games have a native support for 60 fps, but not all of them can reach said frames, even on real hardware. A example of this is Fire Emblem Warriors: Three Hopes, that oscillates between 40 and 50 in heavy battle situations.

In such cases, a fps limiter set to 30 would be better, creating a more stable and consistent experience. The ingame speed limiter can do it (by setting it to 50%), but it also applies to cutscenes that are 30 fps, thus halving it to 15. You can also set it on your gpu control panel, but it's not optimal as it applies to everything, requiring you to open the control panel whenever you want to disable it.

I think a proper fps limiter would be a really good quality of life feature for the emulator.

**Comment by FearlessTobi** [comment]
This is pretty much infeasible because in most games, the game speed is tied to the framerate.
So limiting the FPS to half of their normal value will have the game run at half speed.

Also, even in games where changing the maximum FPS works it can lead to instability and crashes.

Instead of adding game specific hacks for this, we should work on making yuzu run faster in those games.
