### ISSUE TITLE
After I update yuzu from 1277 to 1278 or above version,  if switch to fullscreen or switch back, yuzu will CRASH!!

### ISSUE THREAD

**Issue by timlgy** [yuzu-emu/yuzu#9550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1278

### Description of Issue

After I update yuzu from 1277 to 1278 or above version,  if switch to fullscreen(F11) or switch back, yuzu will CRASH!!

### Expected Behavior

switch to fullscreen(F11)  on Mainline 1277 is OK

### Reproduction Steps

1. load a game in windows mode
2. waiting into game screen
3. F11 to fullscreen
4. no response or CRASH

### Log File

no log

### System Configuration

CPU: i5-12490F
GPU/Driver: 3060/527.56
RAM:32G
OS:Windows11 64

**Comment by german77** [comment]
We are on yuzu 1294. Please update there have been multiple fixes since then.

**Comment by timlgy** [comment]
tried, NOT work on 1294发自我的手机-------- 原始邮件 --------发件人： Narr the Reg ***@***.***>日期： 2023年1月5日周四 00:05收件人： yuzu-emu/yuzu ***@***.***>抄送： "Tim.Liu" ***@***.***>, Author ***@***.***>主    题： Re: [yuzu-emu/yuzu] After I update yuzu from 1277 to 1278 or above version,  if switch to fullscreen or switch back, yuzu will CRASH!! (Issue #9550)
We are on yuzu 1294. Please update there have been multiple fixes since then.

**Comment by timlgy** [comment]
I have no these installed at all. Thanks.发自我的手机-------- 原始邮件 --------发件人： Matías Locatti ***@***.***>日期： 2023年1月5日周四 02:25收件人： yuzu-emu/yuzu ***@***.***>抄送： "Tim.Liu" ***@***.***>, Author ***@***.***>主    题： Re: [yuzu-emu/yuzu] After I update yuzu from 1277 to 1278 or above version,  if switch to fullscreen or switch back, yuzu will CRASH!! (Issue #9550)
Make sure to update/uninstall Rivatuner, HWinfo, or any other OSD overlay.

**Comment by timlgy** [comment]
> We are on yuzu 1294. Please update there have been multiple fixes since then.

Tried every version from 1278 to 1294, only 1277 and below is OK on this issue.

**Comment by timlgy** [comment]
> Make sure to update/uninstall Rivatuner, HWinfo, or any other OSD overlay.

not installed.

**Comment by RokkumanX** [comment]
@timlgy 

I have the same issue as you and I can't go to fullscreen in any of the newer yuzu versions whether it be Mainline or Early Access.

Last known Early Access to fullscreen is 3216 and last known Mainline to fullscreen is 1277.

Every new version results in the image below.

![Fullscreen](https://user-images.githubusercontent.com/85066613/211152751-c74be1b4-67d8-4640-b562-48b761afa157.png)

My specs are as following:

i7 8700K @ stock clock
NVIDIA GTX 1070 using 527.86 drivers
64 GB RAM
Windows 10 Enterprise LTSC 2021

**Comment by german77** [comment]
Mainline 1278 added this PR #9463 however I can't see to be able to replicate this issue. I'm literally entering and leaving fullscreen multiple times a second on different games. Yet everything seem normal

**Comment by RokkumanX** [comment]
First of all let me just say thank you for testing out this for yourself, it means a lot to the little man that staff members and the developers stepping up and investigates the problem.

So, what do we know about this issue, well it seems only to affect some of us (me included)

Just to rule out certain things I will make a "checklist" of things of what I have and is doing.

1. I don't have any form of software that could hinder the ability to utilize yuzu properly, meaning going to fullscreen. My system is strictly a offline gaming system which contains only what it needs and nothing else.

2. Obviously I'm using Windows, but the edition I'm using shouldn't be any problem since the fullscreen ability have worked pretty consistently in yuzu up until now.

3. I'm using NVIDIA's 527.86 drivers which means I'm using Vulkan beta drivers, I have also used WHQL 527.56 and 527.37 which both resulted in not being able to fullscreen in the latest versions of yuzu.

4. I'm using Vulkan (ON), High GPU (ON) and VSync (OFF) in the settings with pretty much the same settings as EA 3216 (which works great)

There is however as I'm typing a newer GPU driver update available, 528.02 which I could install and test out just to be sure but otherwise not much can be said about this and the image above with the yuzu.exe is not responding is pretty much the only thing I see when I update to newer versions of yuzu attempting to fullscreen.

It looks like I might have to keep EA 3216 (15th december 2022) for quite a while. until this have been resolved.

**Comment by KZavi** [comment]
Deleting qt-config.ini in the Appdata/Roaming/yuzu folder usually solves such issues (I recall it has been brought up here before)... but then all it does is to reset all settings back to defaults with no hints to what goes wrong in the first place.

**Comment by RokkumanX** [comment]
I'm afraid to tell you but as an 37 year old emulator user for the past 23-24 years (somewhere around 1999), that's usually the first thing I do when I have issues or updating versions/builds of something.

Deleting configuration/settings is part of Emulation 101 which I get some people don't know or get all the times.

However, there have been a couple of days now and quite a few builds since then so maybe I will try these later when I get home from work this afternoon.

Also, updating to driver 528.02 didn't work either.

**Comment by KZavi** [comment]
Well, setting it up with a new config is what fixed it for me - don't have any issues going fullscreen on the latest EA build now.

**Comment by RokkumanX** [comment]
Thank you @KZavi 
I'm glad to hear that it works for you now!

Which specific build did you use? EA 3301?

This issue is what have stopped me from updating since it always have ended with not responding.

**Comment by KZavi** [comment]
It should be 3303 now. Good luck!

**Comment by RokkumanX** [comment]
Ok, looking forward to test it out soon!

**Comment by RokkumanX** [comment]
Just tested EA 3303 completely fresh and the problem is still there, I can't for the love of god fullscreen without yuzu stops responding.

I'm giving up on this for the time being.

**Comment by RokkumanX** [comment]
Waaaaaaaait, it works??????

I deleted the configuration once more but this time around I didn't change a single setting and it worked right away, all default.

Can it be something with the hotkeys I usually change, I'll have to investigate.

**Comment by RokkumanX** [comment]
I found it, it's the setting Pause emulation when in background that causes this mess.
When its checked yuzu will not fullscreen and stops responding, if I uncheck the setting fullscreen works.

This was not a problem in older versions like EA 3216 or Mainline 1277.

@german77 @goldenx86 

I finally found the culprit!!!!!

**Comment by RokkumanX** [comment]
Mute audio when in background is unaffected, only Pause emulation is affected when fullscreening.

I tested it just for fun.

**Comment by german77** [comment]
I don't get a crash but definitively yuzu get's softlocked. This is something I can fix

**Comment by RokkumanX** [comment]
Thank you very much, this sounds awesome!

Yeah, you're right, it's more of a softlock thing then a crash but it always results in a yuzu.exe is not responding situation.

It feels so great that the issue is going to be fixed.

**Comment by timlgy** [comment]
> 

right

**Comment by timlgy** [comment]
thank you all！
