### ISSUE TITLE
QT5 libs bloating - They are over 200MB!!!

### ISSUE THREAD

**Issue by gsanjin** [yuzu-emu/yuzu#9716]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What feature are you suggesting?

Any plans for debloating, caused by QT5 libs? QT libs are already over 200MB, of which QT5WebEngineCore alone is over 100MB (is that really what we need?)

I am on late July 2022 release yet, as it was one of the last ones with reasonable file/memory sizes.

### Why would this feature be useful?

More reasonable binary file sizes, lesser memory requirements for older computers.

**Comment by theboy181** [comment]
lesser memory requirements for older computers. <-- Can we emulate modern games on older computer. I know this is not an excuse, but this is a puzzling statement.

**Comment by german77** [comment]
yuzu_cmd exist for this reason. Is a light weight version of yuzu without Qt.  Trimming Qt specially the web core is possible but you will loose features such as web applets.

Since the games are a few GB I doubt storage is your problem but rather download time might be an issue. This needs to be improved on the updater as most binaries aren't changed but so far no developer has taken this task.

Closing as the solution is to use yuzu_cmd for lightweight applications.
