### ISSUE TITLE
100% crash while enabled the "Enable Debug Asserts" option

### ISSUE THREAD

**Issue by Ryan2603** [yuzu-emu/yuzu#9808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Main1340 / EA3400

### Description of Issue

as title, just wanna dig something to report but its crashed everytime

### Expected Behavior

i don't know

### Reproduction Steps

enable the debug option then boot a game

### Log File

nope

### System Configuration

CPU: 5700x
GPU/Driver: 3060ti
RAM: 64G
OS: W11

**Comment by german77** [comment]
Then disable it. Debug asserts mean just that the game will fully stop on every little assert even it's not critical. Don't touch debug options if you aren't a developer. Those aren't for normal users to play with.

**Comment by Ryan2603** [comment]
> Then disable it. Debug asserts mean just that the game will fully stop on every little assert even it's not critical. Don't touch debug options if you aren't a developer. Those aren't for normal users to play with.

your sound not fair, definitely not playing, im helping, voluntee, 
i would like to enable all the logs as that can be extremely detail , i do because i wanna help , to improve the dev, perfection.
especially every issue needed a log to prove things, otherwise its got ignored somewhat by the mood. 

you know what? im the passer-by and not really know how the things going on, but "this" is stupid, its crashed without any communication, if you say so, allright, then we should disable the console and shut up.

**Comment by german77** [comment]
I didn't meant to be rude. Normal logs usually provide a lot of details. But for example a log on debug  or trace will provide so much meaningless data that it will effectively hide the real issue from plain sight. 

If you want to get helpful info that isn't obtained from a normal log I suggest running yuzu while using a debugger like visual studio. So on crash you get a stack trace. That's really important for us since it allows us to pin point a specific faulty code.

**Comment by Ryan2603** [comment]
thanks for the reply, i try my best!
