### ISSUE TITLE
Metroid Prime Remastered - Samus and enemies have missing shadows

### ISSUE THREAD

**Issue by lKomus** [yuzu-emu/yuzu#9813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1340

### Description of Issue

On real hardware, the game casts shadows for Samus and enemies like the Space Pirates, but they are not present when playing on Yuzu.
![no shadow](https://user-images.githubusercontent.com/4800879/218890840-47f940f2-9e52-464c-9153-a7a0c43d0ee1.jpg)

### Expected Behavior

Samus and enemies have visible shadows.
![shadow](https://user-images.githubusercontent.com/4800879/218891389-a224c15f-0557-4eca-99ae-0e4919729f2c.png)

### Reproduction Steps

Start a new game and look at Samus when she's on the ground after getting off the ship.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10737845/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5800X
GPU/Driver: NVIDIA Geforce 3060 Ti 8GB (528.02)
RAM: 16GB
OS: Windows 11 Pro 22H2

**Comment by XxAlcatelxX** [comment]
For this kind of situation, you must mention which API you use to play, even so I must mention that it is an emulator problem and there is no way to solve it, it doesn't matter if you use Vulkan or OpenGL... you will still have no shadows. You will ONLY have shadows playing on Ryujinx with OpenGL (since using vulkan on Ryujinx they also disappear), but unfortunately the game has serious problems with textures in which most of the textures just turn BLACK and the game looks horrible. The solution is to wait for a new patch to fix the problem.

**Comment by lKomus** [comment]
Oh yeah I was using Vulkan.
And I know there is no solution right now, but that's the point of opening new issues.

**Comment by Ominousonion666** [comment]
It does render but only sometimes.
![010012101468c000_2023-02-19_14-26-30-803](https://user-images.githubusercontent.com/45669443/219938673-07d07367-5cf5-4ce5-9a5c-8b05d0098725.png)

**Comment by Graslu** [comment]
Yeah it does render sometimes over some surfaces, but it's strange - during the final battle, you can see a shadow below Metroid Prime, but Samus won't cast any.

As already reported by others, Vulkan, 3x scaling.

![Desktop Screenshot 2023 02 21 - 02 24 40 15](https://user-images.githubusercontent.com/34986384/220227692-8fadfaac-f241-413e-909e-e3e5320a2eef.png)

**Comment by theboy181** [comment]
Has to do with Height of objects I think.
![image](https://user-images.githubusercontent.com/9299743/220393604-ce5346f9-8420-48af-8759-f4d415d22053.png)

**Comment by Brochu** [comment]
Hey, I was interested in looking into this issue. I was able to reproduce the issue in the introduction cutscene.

An interesting detail is that sitting on the main menu will play a different version of the intro cutscene because the shadows work in that version
![image](https://user-images.githubusercontent.com/2815498/221208041-03dae475-32a2-4234-80fa-6e691faa0c25.png)

I would like to capture the game with RenderDoc to get more information on what is happening but on my end, launching yuzu-cmd from RenderDoc crashes the emulator after ~50 frames. Is there any setup I need to go through before I can take RenderDoc captures?

**Comment by Graslu** [comment]
The menu previews are pre-recorded videos, that's why the shadows are present there.

**Comment by Brochu** [comment]
Hello,

I was able to iron out the issues I had capturing the game on RenderDoc and I was able to look into this issue a little bit more. My first goal was to find the passes that would produce and use the shadow maps. I captured the moment after Samus gets out of her ship to check out the frame's passes.

 I found a depth-only pass that renders into an image (D16, 256x256) that looks like this:
![9813-ShadowMapWrite](https://user-images.githubusercontent.com/2815498/229718916-e867ba43-5690-486c-b3f3-1fbbc74bb4b2.png)

So I know that the shadow map rendering seems to be working as expected. My next step was to find the pass that uses this texture as a resource in order to render the shadow under Samus. This is the draw call I found that uses the shadow map as a frag shader input.
![9813-ShadowMapRead](https://user-images.githubusercontent.com/2815498/229721907-af3df071-3755-49bb-8943-eb1a63631ee8.png)

From what I understand, this draw is supposed to render the shadow to a triangle placed below the mesh casting the shadow. The vertex input can be seen here for this draw:
![9813-VertInput](https://user-images.githubusercontent.com/2815498/229722181-2ee6b503-2458-4ee2-aa70-b281b259ba3d.png)

I think the problem could be related to the position that the vert shader outputs. It seems like the vertices are all placed outside of the viewport.
![9813-VertShaderOut](https://user-images.githubusercontent.com/2815498/229722279-e36f3f0b-50da-410b-bd9d-63248e4605d6.png)

I took a different capture later on where a shadow was correctly rendered for an enemy and in that case, the triangle where the shadow is rendered is properly placed within the viewport bounds.
![9813-VertShaderOutEnemy](https://user-images.githubusercontent.com/2815498/229722387-9707b501-fa53-411f-a55a-12c97b707ee7.png)

I am not sure how these vertices are provided by the game, or how they are handled by the emulator yet. I just wanted to give a quick run down of what I found on my end. If anyone is more familiar with the emulator can think of something I can look into or some idea of why this is happening, please let me know and I will be happy to look in more details. I will keep looking for more information and maybe which part of the emulator could be causing this.

I am a bit new with the process of working on OSS on Github, so please let me know if there is some information missing that could be helpful for collaboration on this issue.

**Comment by theboy181** [comment]
Amazing work so far! I hope this can be figured out! the missing shadows makes the game look flat! Im sure fixing this will make it in the next yuzu article too!

**Comment by lKomus** [comment]
Fixed by https://github.com/yuzu-emu/yuzu/pull/11225
